<?php $this->headTitle()->append('Devis Retraite'); ?>
<div class="row" id="devis">
	<br><a id="boutonRetour" href="<?php echo $this->url(array('controller'=>'xylavie','action'=>'index'), null, true);?>" class="btn"><i class="icon-arrow-left"></i> Retour</a>
	<div class="span12" id="retraite">
		<h2>Demande de devis Retraite</h2>
		<p>Afin d'améliorer la qualité de nos réponses, tous les champs sont obligatoires.</p>
		<hr>
		<span style="margin-left: 90px;" class="label label-important">Attention</span><h4 style="display:inline;font-size:0.7em">  Veillez à être concis et ne pas faire d'erreurs dans vos coordonnées</h4>
		<?php echo $this->form; ?>
		<br>
		<div class="pager">
			<a href="#" id="validRetraite" onclick="_gaq.push(['_trackEvent', 'Clic sur Envoyer Devis Retraite', 'envoi']); return false;">Envoyer</a>
		</div>
		<p>Une fois votre devis envoyé nous ferons tout notre possible pour répondre dans les 48h.</p>
	</div>
</div>
<br>