<?php $this->headTitle()->append('Signaler une erreur'); ?>
<?php $this->headScript()->appendFile('/js/tiny.js'); ?>
<br>
<br>
<h1>Signaler erreur XYLAGROUP</h1>

<div class="row">
	<div class="span12">
		<h2>Signaler une erreur</h2>
		<?php echo $this->form; ?>
		<div class="pager" style="text-align:left">
			<a href="#" id="validSignaler" onclick="return false;" style="margin-left:50px;">Envoyer</a>
		</div>
	</div>
</div>
