<!-- <div class="row">
	<div class="span12">
		<?php //echo var_dump($this->mdp); ?>
		<?php //echo var_dump($this->encod); ?>
	</div>
</div> -->
<?php $this->headTitle()->append('Contact XYLAGROUP'); ?>
<br>
<br>
<h1>Contact XYLAGROUP</h1>
<div class="row">
	<div class="enveloppe" id="write">
		<div id="beforeForm">
			<span class="label label-important">Attention</span><h4 style="display:inline;font-size:0.7em">  Veillez à être concis et ne pas faire d'erreurs dans vos coordonnées</h4><h3 id="replace">XYLAGROUP</h3>
		</div>
		<br>
		<?php echo $this->form; ?>
		<div class="pager" style="text-align:left;margin-left : 150px">
			<a href="#" id="validContact" onclick="return false;">Envoyer</a>
		</div>
	</div>
</div>
