<?php $this->headTitle()->append('Mentions Légales'); ?>
<br>
<br>
<h1>Mentions Légales</h1>
<div class="row">
	<div class="span12">
		<h2>Mentions Légales</h2><br><br>
		<div id="content" class="shadow">
			<div class="wysiwyg global">
				<p><strong>Le site www.xylagroup.fr<br /></strong><strong><br /></strong></p>
				<h3><strong>Editeur</strong></h3>
				<p>Ce site est produit par la soci&eacute;t&eacute; XYLAGROUP</p>
				<p>Si&egrave;ge social 3 Chemin de Parenty 69250 Neuville sur Sa&ocirc;ne - www.xylagroup.fr </p>
				<h3><strong>Directeur de la publication</strong></h3>
				<p>Jean Marc VOISIN</p>
				<h3><strong>Coordonn&eacute;es</strong></h3>
				<p>3 Chemin de Parenty</p>
				<p>69250 Neuville sur Sa&ocirc;ne</p>
				<p>T&eacute;l. 04 78 98 24 76</p>
				<h3><strong>Propri&eacute;t&eacute;</strong></h3>
				<p>Le site et son contenu font l'objet d'une protection l&eacute;gale au titre de la propri&eacute;t&eacute; litt&eacute;raire et artistique et de la propri&eacute;t&eacute; industrielle.<br />Il est interdit &agrave; tout internaute de copier ou reproduire tout ou partie du contenu du site, sauf pour son usage propre et sauf autorisation sp&eacute;cifique. Copyright XYLAGROUP Tous droits r&eacute;serv&eacute;s.<strong><br /><br /></strong></p>
				<h3><strong><strong>Validit&eacute; des informations<br /></strong></strong></h3>
				<p>Les informations fournies sur ce site sont pr&eacute;sent&eacute;es &agrave; titre indicatif et g&eacute;n&eacute;ral et ne sauraient &ecirc;tre utilis&eacute;es sans v&eacute;rifications pr&eacute;alables par l'internaute.<br />XYLAGROUP ne pourra &ecirc;tre tenu pour responsable des cons&eacute;quences directes ou indirectes pouvant r&eacute;sulter de l'utilisation, la consultation et l'interpr&eacute;tation des informations fournies, ni de la modification des dispositions administratives et juridiques survenant apr&egrave;s la publication.</p>
				<h3><strong>Liens entre sites internet</strong></h3>
				<p>XYLAGROUP propose des liens vers des sites internet ext&eacute;rieurs. Leur contenu ne peut en aucune mani&egrave;re engager la responsabilit&eacute; de XYLAGROUP.<br />Tout lien depuis un site internet ext&eacute;rieur vers xylagroup.fr doit faire l'objet d'une autorisation pr&eacute;alable de XYLAGROUP et donc de son dirigeant.</p>
				<h3><strong>El&eacute;ments techniques - r&eacute;alisation</strong></h3>
				<p>Le site est r&eacute;alis&eacute; par M. MARTINEZ Pierre Julien, gr&acirc;ce au Framework Zend.</p>
				<p>&nbsp;</p>
				<h3><strong>Protection des droits de l'internaute</strong><strong><strong><br /><br /></strong></strong></h3>
				<ul>
				<li><strong>Formulaires</strong><br />Nous proposons sur le site www.xylagroup.fr un certain nombre de formulaires qui nous permettent de mieux cibler les demandes des internautes et d'&ecirc;tre s&ucirc;r d'obtenir les informations indispensables pour pouvoir y donner suite.<br />L'internaute est bien entendu libre de ne pas remplir ces formulaires. Cependant, il est indispensable de remplir certains d'entre eux afin de pouvoir donner suite aux demandes de devis.<br />En remplissant ces formulaires, l'internaute transmet des informations qui pourront &ecirc;tre utilis&eacute;es par la soci&eacute;t&eacute; XYLAGROUP.</li>
				</ul>
				<br />
				<ul>
				<li><strong>Envoi d'e-mail</strong><br />En utilisant un logiciel de messagerie, l'internaute nous communique son adresse &eacute;lectronique. Celle-ci peut &ecirc;tre conserv&eacute;e et utilis&eacute;e ult&eacute;rieurement pour proposer des offres commerciales ou des services analogues.</li>
				</ul>
				<br />
				<ul>
				<li><strong>Protection des donn&eacute;es personnelles</strong><br />Les informations personnelles recueillies :<br />- font l'objet d'un traitement sp&eacute;cifique<br />- sont utilis&eacute;es pour r&eacute;pondre aux diff&eacute;rents services propos&eacute;s par le site<br /><br /><br />Loi Informatique et Libert&eacute;s du 6 janvier 1978 : vous disposez d'un droit d'acc&egrave;s, de rectification et d'opposition sur les informations vous concernant ; ces informations sont destin&eacute;es &agrave; XYLAGROUP. Vous disposez du droit de vous opposer &agrave; ce que ces donn&eacute;es fassent l'objet d'un traitement &agrave; des fins de prospection ou soient transmises &agrave; des tiers. <br /><br />Comment exercer ce droit ou obtenir des informations compl&eacute;mentaires ?<br /><br />- en nous contactant en <a href="<?php echo $this->url(array('controller'=>'pages','action'=>'contact'), null, true);?>">cliquant ici</a><strong> <br /></strong></li>
				</ul>
				<br />
				<h3><strong>Configuration technique</strong></h3>
				<p>Le site xylagroup.fr est optimis&eacute; :<br />- pour un affichage 1024 x 768 pixels<br />- pour les navigateurs Internet Explorer 8.0 et suivants, Mozilla Firefox 10.0 et suivants, Opera 11.0 et suivants, Safari 5.0 et suivants, Google Chrome 18.0 et suivants.<br /><br />Pour lire certaines informations sur ce site, il faut poss&eacute;der le plugin suivant :<br />- <a href="http://get.adobe.com/fr/reader/">Adobe Reader</a> pour lire ou t&eacute;l&eacute;charger les documents au format PDF.</p>
				<br>
				<h3>Liste des Soci&eacute;t&eacute;s de XYLAGROUP pr&eacute;sentent sur le site :</h3>

				<table class="table table-striped table-bordered table-condensed">
					<thead>
						<tr>
							<th>Entité</th>
							<th>N° RCS</th>
							<th>N° ORIAS</th>
							<th>Adresse</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>XYLASSUR</td>
							<td>433 301 256</td>
							<td>07001095</td>
							<td>3 Chemin de Parenty 69250 NEUVILLE SUR SAONE</td>
						</tr>
						<tr>
							<td>XYLAVIE</td>
							<td>492 320 320</td>
							<td>07007951</td>
							<td>3 Chemin de Parenty 69250 NEUVILLE SUR SAONE</td>
						</tr>
						<tr>
							<td>XYLABTP</td>
							<td>441 620 770</td>
							<td>07005988</td>
							<td>3 Chemin de Parenty 69250 NEUVILLE SUR SAONE</td>
						</tr>
						<tr>
							<td>XYLARISK</td>
							<td>En cours de création</td>
							<td>En cours de création</td>
							<td>3 Chemin de Parenty 69250 NEUVILLE SUR SAONE</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<br>
