<div class="logo">			
	<img src="<?php echo $this->baseUrl;?>/images/bandeaux/<?php echo $this->nomXyla;?>.jpg" alt="<?php echo $this->nomXyla;?>">
</div>

<div class="row">
	<div class="span9">
		<!-- <div class="menuFlou">
			<ul>
				<li><a href="#">Comptabilité</a></li>
				<li><a href="#">Assurance</a></li>
				<li><a href="#">Ressources</a></li>
				<li><a href="#">Web</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</div> -->


		<ul id="tab" class="nav nav-tabs">
			<li class="active"><a href="#home" data-toggle="tab">Home</a></li>
			<li><a href="#profile" data-toggle="tab">Profile</a></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><a href="#dropdown1" data-toggle="tab">@fadfiglvhshfvpisgiowbifvwb</a></li>
					<li><a href="#dropdown2" data-toggle="tab">@mdo</a></li>
				</ul>
			</li> 
		</ul>

		<div id="myTabContent" class="tab-content">
			<div class="tab-pane fade in active" id="home">
				<p>jjjjjjjjjjjiiiiiiiiiiiiiiiiii BBB.</p>
			</div>
			<div class="tab-pane fade" id="profile">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ull.</p>
			</div>
			<div class="tab-pane fade" id="dropdown1">
				<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
			</div>
			<div class="tab-pane fade" id="dropdown2">
				<p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
			</div>
		</div>
	</div>
	<div class="span3">
		<h3><?php echo $this->title; ?></h3>
	</div>
</div>
