<?php $this->headTitle()->append('Xylagroup'); ?>
<br>
<br>
<h1>XYLAGROUP</h1>
<div class="row">

	<H2>TEST</H2>
	<?php if(empty($this->test))
		echo 'vide';
		else echo 'pas vide';
		 ?>

	<?php foreach ($this->encadreAccueil as $e): ?>
		<div class="span12">
			<h2><?php echo $e->titre; ?></h2>
			<br>
			<?php echo ($e->contenu != "<news>") ? $e->contenu : "ICI les News a voir plus tard" ?>
			<!-- NEWS -->
			<!-- FIN NEWS -->
			<hr class="soften">
		</div>
			<br>
			<!-- ICI A TESTER SI C'EST VIDE OU NON -->
			<div class="span5">
				<ul id="tab" class="nav nav-pills nav-stacked">
					<?php $i =0;
					foreach ($e->sousencad as $s) : 
						echo ($i == 0) ? '<li class="active">' : '<li>' ; 
						$ident = explode(" ", $s->titre);
						echo '<a href="#'.$ident[0].'" data-toggle="tab">'.$s->titre.'</a></li>';
						$i++;
					endforeach; 
					?>
				</ul>
			</div>
			<div class="span7" id="alignLeft">
				<div id="myTabContent" class="tab-content">
					<?php 
					$j = 0;
					foreach ($e->sousencad as $s) : 
						$ident = explode(" ", $s->titre);
						echo ($j == 0) ? '<div class="tab-pane fade in active" id="'.$ident[0].'">' : '<div class="tab-pane fade" id="'.$ident[0].'">';
						echo $s->contenu;
						echo '</div>';
						$j++;
					endforeach; 
					?>
				</div>
			</div>
	<?php endforeach ?>
</div>