<?php $this->headTitle()->append('La News du Jour'); ?>
<br>
<br>
<h1>News du jour</h1>
<?php $news = $this->theNews[0]; ?>
<h2>News #<?php echo $news->numero;?></h2><br>
<div id="row-encadre" class="row">
	<div class="span5">
		<?php echo '<img src="'. $this->baseUrl.'/images/news/'.$news->photo.'" alt="News #'.$news->numero.'">' ?>
	</div>
	<div class="span6">
		<h3><?php echo $news->titre; ?></h3>
	</div>

	
	<div class="span12">
		<?php echo $news->contenu; ?>
	</div>
	<div class="span6">
		<h5>News créée par <?php echo $news->auteur; ?> le <?php echo $news->date; ?>.</h5>
	</div>
	<div class="span12">
		<?php if (strlen ($news->lien) !=0 ) { ?>
			<p><span id="source">Source :</span> <a href="http://<?php echo $news->lien;?>" title="Source"><?php echo $news->lien;?></a></p>
		<?php } ?>
	</div>
</div>
<br>
<div class="row">
	<div class="span12">
		<a href="" title="">ICI Le lien vers les anciennes news + la news du jour (classées par ordre decroissant !)</a>
	</div>
</div>

