<div style='background-color:#759ebb; width:100%; padding: 50px 0;'>
	<div style='background: #fff; margin: auto; width: 800px; font-size: 14px; font-family: "Trebuchet Ms",Arial; color: #333; text-align: justify;'>
		<div>
			<div style='border-bottom: 2px solid #e0e0e0; text-align:center'>
				<a style='display: block; text-decoration: none' href='http://www.xylagroup.fr/'>
					<img src='http://www.xylagroup.fr/bando.png'>
				</a>
				<div style="text-align: center; border-top: 2px solid #e0e0e0; padding-top : 14px; margin-bottom: 10px;">
					<a style='text-decoration: none; margin: 0 30px 0 20px' href="http://www.xylagroup.fr/xylassur">
						<img style='height:20px;' src="http://www.xylagroup.fr/XYLASSUR.jpg">
					</a>
					<a style='text-decoration: none; margin: 0 30px 0 0' href="http://www.xylagroup.fr/xylavie">
						<img style='height: 20px;' src="http://www.xylagroup.fr/XYLAVIE.jpg">
					</a>
					<a style='text-decoration: none; margin: 0 30px 0 0' href="http://www.xylagroup.fr/xylabtp">
						<img style='height: 20px;' src="http://www.xylagroup.fr/XYLABTP.jpg">
					</a>
					<a style='text-decoration: none; margin: 0 30px 0 0' href="http://www.xylagroup.fr/xylarisk">
						<img style='height: 20px;' src="http://www.xylagroup.fr/XYLARISK.jpg">
					</a>
				</div>
			</div>
			<div style='background-color: #fff; padding: 15px; margin-bottom: 50px; font-weight:bold;'>
				<?php echo $this->layout()->content ?>
			</div>
			<div>
				<p style="margin:0 0 0 0; padding-bottom: 5px; font-size: 0.8em; border-bottom: 2px solid #e0e0e0;"><span style="margin-left:10px;">Ceci est un email automatique, merci de ne pas y répondre.</span></p>
				<p style="margin: 5px 0 0 10px;"><a style="text-decoration:none;  font-weight:bold; " href=""><span style="color:#9ebad1;">www.</span><span style="color:#4c657d;">xylagroup</span><span style="color:#9ebad1;">.fr</span></a></p>
				<img  src="http://www.xylagroup.fr/footer3.png">
			</div>
		</div>
	</div>
</div>

