<div style='background-color:#fff6d9; width:100%; padding: 50px 0;'>
	<div style='background: #fff; margin: auto; width: 600px; font-size: 14px; font-weight:bold; font-family: "Trebuchet Ms",Arial; color: #333; text-align: justify;'>
		<div>
			<div style='border-bottom: 2px solid #e0e0e0;'>
				<a style='display: block; text-decoration: none' href='http://www.lepirecvvideo.com/'>
					<img src='http://www.lepirecvvideo.com/images/mails/concours-cv-video.png'>
				</a>
				<div style="text-align: center; margin-bottom: 15px;">
					<a style='text-decoration: none; margin: 0 2px' href="http://www.wizbii.com/">
						<img style='height:33px;' src="http://www.lepirecvvideo.com/images/logos/wizbii.png">
					</a>
					<img style='height: 28px;' src="http://www.lepirecvvideo.com/images/logos/ses-partenaires.png" style="margin: 0 0;">
					<a style='text-decoration: none; margin: 0 2px' href="http://www.dailymotion.com/fr/">
						<img style='height: 25px;' src="http://www.lepirecvvideo.com/images/logos/dailymotion.png">
					</a>
					<a style='text-decoration: none; margin: 0 2px' href="http://www.mediaetudiant.fr/" style="margin: 0 0;">
						<img style='height: 25px;' src="http://www.lepirecvvideo.com/images/logos/media-etudiant.png">
					</a>
					<a style='text-decoration: none; margin: 0 2px' href="http://www.youseemii.fr/">
						<img style='height: 25px;' src="http://www.lepirecvvideo.com/images/logos/youseemi.png">
					</a>
					<a style='text-decoration: none; margin: 0 2px' href="http://www.yokoro.fr/" style="margin: 0 0;">
						<img style='height: 25px;' src="http://www.lepirecvvideo.com/images/logos/yokoro.png">
					</a>
					<a style='text-decoration: none; margin: 0 2px' href="http://www.regionsjob.com/" style="position: relative; top: -5px;">
						<img style='height: 25px;' src="http://www.lepirecvvideo.com/images/logos/regionsjob.png">
					</a>
				</div>
			</div>
			<div style='background-color: #fff; padding: 15px; margin-bottom: 50px;'>
				<?php echo $this->layout()->content ?>
			</div>
			<div>
				<a style='text-decoration: none' href='http://www.wizbii.com/'>
					<img src="http://www.lepirecvvideo.com/images/mails/footer.png">
				</a>
			</div>
		</div>
	</div>
</div>

