<div style='background-color:#759ebb; width:100%; padding: 50px 0;'>
	<div style='background: #fff; margin: auto; width: 800px; font-size: 14px; font-family: "Trebuchet Ms",Arial; color: #333; text-align: justify;'>
		<div>
			<div style='border-bottom: 2px solid #e0e0e0; text-align:center'>
				<a style='display: block; text-decoration: none' href='http://www.xylagroup.fr/'>
					<img src='http://www.xylagroup.fr/bando.png'>
				</a>
			</div>
			<div style='background-color: #fff; padding: 15px; margin-bottom: 50px;'>
				<?php echo $this->layout()->content ?>
			</div>
		</div>
	</div>
</div>

