<?php $this->headTitle()->append('Les News'); ?>
<br>
<br>
<h1>Les News</h1>

<div class="row">
	<div class="span12">
		<h2>Liste de toutes les News</h2>
		<?php foreach ($this->autres as $autresN) : ?>
			<div class="little">

				<div id="imageNews">
					<?php echo '<img src="'. $this->baseUrl.'/images/logo/X.png" alt="News #'.$autresN->numero.'">' ?>
				</div>
	 			<div id="titreNews">
					<?php echo '<h4>'.$autresN->titre.'</h4>'; ?>
				</div>
	 			<div id="numNews">
					<?php echo '#'.$autresN->numero; ?>
				</div>

				<?php  $nb_mots = 10;
					$inter = $autresN->contenu;
					$texte = explode(' ', $inter, $nb_mots+1);
					unset($texte[$nb_mots]);?>

				<div id="contenuNews">
					<?php echo implode(' ', $texte).'...';?>
				</div>
				<a href="<?php echo $this->url(array('controller'=>'news',
									'action'=>'newsvue',
									'id' => $autresN->id), null, true);?>">(Lire le suite...)</a>
			</div>
		<?php endforeach; ?>
		</div>
</div>