<?php $news = $this->theNews[0]; ?>
<?php $this->headTitle()->append('News #'.$news->numero); ?>
<br>
<br>
<h1>News</h1>

<?php $news = $this->theNews[0]; ?>

<h2 style="margin-left:5%">News #<?php echo $news->numero;?></h2><br>

<div id="vueSeule" class="row">
	<div class="span5">
		<?php echo '<img src="'. $this->baseUrl.'/images/news/'.$news->photo.'" alt="News #'.$news->numero.'">' ?>
	</div>
	<div class="span6">
		<h3><?php echo $news->titre; ?></h3>
	</div>

	
	<div class="span12">
		<?php echo $news->contenu; ?>
	</div>
	<div class="span6">
		<h5>News créée par <?php echo $news->auteur; ?> le <?php echo $news->date; ?>.</h5>
	</div>
	<div class="span12">
		<?php if (strlen ($news->lien) !=0 ) { ?>
			<p><span id="source">Source :</span> <a href="<?php echo $news->lien;?>" title="Source"><?php echo $news->lien;?></a></p>
		<?php } ?>
	</div>
</div>

<br><br>

<div class="row">
	<div class="span12">
		<?php if  (($this->nPrec[0]->date != null) || ($this->nNext[0]->date != null)) { ?>
			<ul class="pager">
				<?php if ($this->nPrec[0]->date != null) { ?>
					<li class="previous"><a href="<?php echo $this->url(array('controller'=>'news',
	 											'action'=>'newsvue',
	 											'id' => $this->nPrec[0]->id), null, true);?>">&larr; News Précédente</a></li>
				<?php } if ($this->nNext[0]->date != null) { ?>
					<li class="next"><a href="<?php echo $this->url(array('controller'=>'news',
	 											'action'=>'newsvue',
	 											'id' => $this->nNext[0]->id), null, true);?>">News Suivante &rarr;</a></li>
				<?php } ?>
			</ul>
		<?php } ?>
		<br><br>
		<p><a href="<?php echo $this->url(array('controller'=>'news',
	                				 	'action'=>'index'), null, true);?>">> Accéder à toutes les news <</a></p>
	</div>
</div>
<br>