<body>
<p><span style="font-weight:bold">Bonjour, <br><br>En date du <?php echo $this->date; ?>, la société <?php echo $this->controller; ?> a reçu un message de la part de <?php echo $this->civilite; ?> <?php echo $this->nom; ?></span><br><br><?php echo $this->message; ?><br>Ses coordonnées sont les suivantes : <br>Email : <?php echo $this->mail; ?><br>Tel : <?php echo $this->tel; ?><br><br>Bonne journée<p>

</body>