<?php $this->headTitle()->append('Confirmation Devis Garanties Accidents de la vie'); ?>

<br>
<h1>Confirmation Devis XYLAVIE</h1>

<div class="row" id="confirmation">
	<?php $contrat = $this->infos["contrat"]; ?>
	<div class="span12">
		<h2>Choix du moyen de paiement</h2>
		<br>
		<p><span class="tabul">Suite</span> à l'études des informations que vous nous avez transmises à l'écran précédent, nous avons determiné le tarif qui vous convenait le mieux.</p>
<!-- 		<br>
		<p>Vous voulez donc souscrire un contrat <span style="font-weight:bold"><?php echo $contrat; ?></span>, ainsi le tarif est le suivant : </p>
		<br> -->
<!-- 		<div id="prix">
			<h3></h3>
		</div> -->
<!-- 		<br> -->
		<p><span class="tabul">Pour</span> souscrire un contrat GAV (Garanties des Accidents de la Vie) vous devez cliquer sur le moyen de paiment que vous souhaitez. Voici les deux offres que nous vous proposons pour votre choix de contrat <span style="font-weight:bold"><?php echo $contrat; ?></span> : </p>
		<div class="row">
			<br>
			<a href="#" id="carte" onclick="return false;" title="Prélèvement automatique">
				<div class="span6" id="card">
					<p class="prix"><?php echo ($contrat == "Individuel") ? '11' : '20'; ?></p>
					<img src="<?php echo $this->baseUrl; ?>/images/xylavie/cardFF.jpg">
				</div>
			</a>
			<a href="#" id ="cheque" onclick="return false;" title="Chèque annuel">
				<div class="span6" id="check">
					<p class="prix"><?php echo ($contrat == "Individuel") ? '132' : '240'; ?></p>
					<img src="<?php echo $this->baseUrl; ?>/images/xylavie/checkFF.jpg">
				</div>
			</a>
			<br><br>
			<div class="span12">
				<p id="avert">Ce choix n'engage en rien, et aucun paiement n'est demandé sur ce site.</p>
			</div>
			<br><br>
			<div class="span12">
				<form enctype="application/x-www-form-urlencoded" action="" method="post">
				<table>
					<?php echo $this->form->hide; ?>
					<?php echo $this->form->cg; ?>
					
				</table>
			</div>
			<div class="pager">
				<a href="#" id="validSouscription" onclick="return false;">Envoyer</a>
			</div>
		</div>
		<?php //echo var_dump($this->infos); ?>
	</div>
</div>
