<?php $this->headTitle()->append('Devis Garanties Accidents de la Vie'); ?>
<div class="row" id="devis">
	<br><a id="boutonRetour" href="<?php echo $this->url(array('controller'=>'xylavie','action'=>'index'), null, true);?>" class="btn"><i class="icon-arrow-left"></i> Retour</a>
	<div class="span12" id="accident">
		<h2>Demande de devis Garanties Accidents de la vie </h2>
		<p>Afin d'améliorer la qualité de nos réponses, tous les champs sont obligatoires.</p>
		<hr>
		<span style="margin-left: 90px;" class="label label-important">Attention</span><h4 style="display:inline;font-size:0.7em">  Veillez à être concis et ne pas faire d'erreurs dans vos coordonnées</h4>
		<form id="s" enctype="application/x-www-form-urlencoded" action="" method="post">
			<table>
				<?php echo $this->form->civ; ?>
				<?php echo $this->form->nom; ?>
				<?php echo $this->form->prenom; ?>
				<?php echo $this->form->dateN; ?>
				<?php echo $this->form->email; ?>
				<?php echo $this->form->telephone; ?>
				<?php echo $this->form->adresse; ?>
				<?php echo $this->form->codeP; ?>
				<?php echo $this->form->ville; ?>
				<?php echo $this->form->contrat; ?>
			</table>
			<div id="familial">
				<br><br><hr><br>
				<table>
					<h3>Votre Famille</h3><br>
					<?php echo $this->form->conjoint; ?>
					<?php echo $this->form->civC; ?>
					<?php echo $this->form->nomC; ?>
					<?php echo $this->form->prenomC; ?>
					<?php echo $this->form->dateC; ?>
					<?php echo $this->form->nombreenfant; ?>
				</table>
			</div>
			<div id="enfant1">
				<table>
					<?php echo $this->form->nom1; ?>
					<?php echo $this->form->prenom1; ?>
					<?php echo $this->form->date1; ?>
				</table>
			</div>
			<div id="enfant2">
				<table>
					<?php echo $this->form->nom2; ?>
					<?php echo $this->form->prenom2; ?>
					<?php echo $this->form->date2; ?>
				</table>
			</div>
			<div id="enfant3">
				<table>
					<?php echo $this->form->nom3; ?>
					<?php echo $this->form->prenom3; ?>
					<?php echo $this->form->date3; ?>
				</table>
			</div>
			<div id="enfant4">
				<table>
					<?php echo $this->form->nom4; ?>
					<?php echo $this->form->prenom4; ?>
					<?php echo $this->form->date4; ?>
				</table>
			</div>
			<div id="enfant5">
				<table>
					<?php echo $this->form->nom5; ?>
					<?php echo $this->form->prenom5; ?>
					<?php echo $this->form->date5; ?>
				</table>
			</div>
			<br>
			<div class="pager">
				<a href="#" id="validAccident" onclick="_gaq.push(['_trackEvent', 'Clic sur Première étape GAV', 'clic']); return false;">Passer à la dernière étape</a>
			</div>
	</div>
</div>
<div class="row" id="confirmation">
	<div class="span12" style="margin-top: 5%">
		<h2>Choix du moyen de paiement</h2>
		<br>
		<p><span class="tabul">Suite</span> à l'études des informations que vous nous avez transmises à l'écran précédent, nous avons determiné le tarif qui vous convenait le mieux.</p>

		<p><span class="tabul">Pour</span> souscrire un contrat GAV (Garanties des Accidents de la Vie) vous devez cliquer sur le moyen de paiment que vous souhaitez. Voici les deux offres que nous vous proposons pour votre choix de contrat <span id="typeC" style="font-weight:bold"></span> : </p>
		<div class="row">
			<br>
			<a href="#" id="carte" onclick="return false;" title="Prélèvement automatique">
				<div class="span6" id="card">
					<p class="prix"></p>
					<img src="<?php echo $this->baseUrl; ?>/images/xylavie/cardFF.jpg">
				</div>
			</a>
			<a href="#" id ="cheque" onclick="return false;" title="Chèque annuel">
				<div class="span6" id="check">
					<p class="prix2"></p>
					<img src="<?php echo $this->baseUrl; ?>/images/xylavie/checkFF.jpg">
				</div>
			</a>
			<br><br>
			<div class="span12">
				<p id="avert">Ce choix n'engage en rien, et aucun paiement n'est demandé sur ce site.</p>
			</div>
			<br><br>
			<div class="span12" style="margin-bottom : 15px">
				<table> <?php echo $this->form->hide; ?> </table>
					<a onclick="_gaq.push(['_trackEvent', 'Clic sur Voir les CGV (GAV)', 'clic'])" id="conditions" href="<?php echo $this->baseUrl; ?>/images/xylavie/CG contrat GAV.pdf" target="_blank" title="Conditions Générales du contrat">Voir les conditions générales</a>
				<table> <?php echo $this->form->cg; ?> </table>
		</form> <!-- FERMETURE du FORMULAIRE -->
			</div>
			<div class="pager">
				<a href="#" id="validSouscription" onclick="_gaq.push(['_trackEvent', 'Clic sur Envoyer Devis GAV', 'envoi']); return false;">Je souscris mon contrat</a>
			</div>
		</div>
	</div>
</div>
<br>