<?php $this->headTitle()->append('Devis Retraite'); ?>
<div class="row" id="devis">
	<div class="span12" id="retraite">
		<h2>Demande de devis Retraite</h2>
		<p>Afin d'améliorer la qualité de nos réponses, tous les champs sont obligatoires.</p>
		<hr>
		<?php echo $this->form; ?>
		<p>Une fois votre devis envoyé nous ferons tout notre possible pour répondre dans les 48h.</p>
	</div>
</div>

<br>
