<?php $this->headTitle()->append('Devis Santé'); ?>
<div class="row" id="devis">
	<div class="span12" id="sante">
		<h2>Demande de devis Santé</h2>
		<p>Afin d'améliorer la qualité de nos réponses, tous les champs sont obligatoires.</p>
		<hr>

		<form enctype="application/x-www-form-urlencoded" action="" method="post">
				<div id="un">
					<table>
						<?php echo $this->form->civ; ?>
						<?php echo $this->form->nom; ?>
						<?php echo $this->form->prenom; ?>	
						<?php echo $this->form->dateN; ?>
						<?php echo $this->form->email; ?>
						<?php echo $this->form->nbenfant; ?>
						<?php echo $this->form->codeP; ?>
						<?php echo $this->form->ville; ?>
					</table>
				<div class="pager">
					<a href="#" id="next" onclick="return false;">Valider et passer à la suite</a>
				</div>

				</div>

				<div id="deux">
					<table>
						<?php echo $this->form->prenom; ?>	
					</table>
				<div class="pager">
					<a href="#" id="next" onclick="return false;">Valider et passer à la suite</a>
				</div>

				</div>
				<div id="trois">
					<table>
						<?php echo $this->form->dateN; ?>
					</table>
				<div class="pager">
					<a href="#" id="next" onclick="return false;">Valider et passer à la suite</a>
				</div>

				</div>
				<div id="quatre">
					<table>
						<?php echo $this->form->profession; ?>
						<?php echo $this->form->submit; ?>
					</table>
				</div>
				<!-- <div class="QapTcha"></div> -->
		</form>
		<p>Une fois votre devis envoyé nous ferons tout notre possible pour répondre dans les 48h.</p>
	</div>
</div>

<br>