<?php $this->headTitle()->append('Xylavie'); ?>
<div class="logo">			
	<img src="<?php echo $this->baseUrl;?>/images/bandeaux/<?php echo $this->controller;?>.png" alt="<?php echo $this->controller;?>">
</div>
<br><br>
<h1>XYLAVIE</h1>
<?php if ((count($this->first) == 0) and (count($this->else) == 0))
	echo '<h2> Nous sommes désolé mais cette page ne contient pour le moment aucun contenu, ceci devrait être rectifié d\'ici quelques jours!</h2>';
else {?>
	<div class="row">
		<div id="titreH" class="span12 ajout">
			<h2><?php echo $this->first[0]->titre; ?></h2><br>
			<p><a href="<?php echo $this->url(array('controller'=>$this->controller,'action'=>'contact'), null, true) ?>" title="Contactez nous !"><img src="<?php echo $this->baseUrl ?>/images/contact/xylavieContact.png"></a></p>
			<?php echo $this->first[0]->contenu;
				echo $this->partial('partials/affLoop.phtml', array('e' => $this->first[0])); ?>
				<h2 style="color:#5AA2CE;">Vous êtes client ou affilié ?</h2><br>

 				<div class="row">
					<div class="span12 ajout">
						<h2><?php echo $this->rbt[0]->titre; ?></h2><br>
						<p><a href="http://www.gmcgestion.fr" title="Faire une demande de devis"><img src="<?php echo $this->baseUrl; ?>/images/xylavie/rbt3.png"></a></p>
						<p><?php echo $this->rbt[0]->contenu; ?></p>
						<?php //echo $this->partial('partials/affLoop.phtml', array('e' => $this->rbt[0])); ?>
					</div>
					<div class="span12">
						<hr class="soften">
					</div>
				</div>	

			<ul class="nav nav-tabs">
				<h2>Nos offres et nos devis <small style="font-size:0.65em; color:#235D7F;"> Pour les particuliers</small></h2><br>
				<?php $i =0;
					foreach ($this->else as $autres) : 
						echo ($i == 0) ? '<li class="active">' : '<li>' ; 
						$lien = $autres->id + 2000;
						echo '<a href="#'.$lien.'" data-toggle="tab" title="Vous dirige vers '.$autres->titre.'">'.$autres->titre.'</a></li>';
						$i++;
					endforeach; ?>
			</ul>
			<div class="tab-content">
					<?php 
					$j = 0;
					foreach ($this->else as $autres) : 
						$lien = $autres->id + 2000;
						$title = str_replace(array(' ','à', 'â', 'ä', 'á', 'ã', 'å','î', 'ï', 'ì', 'í', 'ô', 'ö', 'ò', 'ó', 'õ', 'ø', 'ù', 'û', 'ü', 'ú', 'é', 'è', 'ê', 'ë', 'ç', 'ÿ', 'ñ', ),
							array('', 'a', 'a', 'a', 'a', 'a', 'a', 'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u', 'u', 'e', 'e', 'e', 'e', 'c', 'y', 'n', ),$autres->titre);
						echo ($j == 0) ? '<div class="tab-pane active" id="'.$lien.'">' : '<div class="tab-pane" id="'.$lien.'">';
						echo '<div class="row">';
						// on test la valeur de ajout
							echo '<div class="span12 ajout">
								<h2>'.$autres->titre.'</h2><br>';
								switch($autres->ajout) {
									case "r": echo '<p><a href="http://www.gmcgestion.fr" title="Faire une demande de devis"><img src="'.$this->baseUrl.'/images/xylavie/rbt3.png"></a></p>'; break;
									case "d": echo '<a href="'.$this->url(array('controller'=>$this->controller,'action'=> 'devis'.strtolower($title).''), null, true).'" title="Faire une demande de devis"><p><img src="'.$this->baseUrl.'/images/using/devis.png"></p><p id="lentite">'.$autres->titre.'</p></a>'; break;
									case "c": echo '<p><a href="'.$this->url(array('controller'=>$this->controller,'action'=> strtolower($title)), null, true).'" title="Contactez nous !"><img src="'.$this->baseUrl.'/images/xylavie/contact.png"></a></p>'; break;
									default: break;
								}
								echo $autres->contenu;
								echo $this->partial('partials/affLoop.phtml', array('e' => $autres));
							echo '</div>';
						echo '</div>'; //ceklui de row
						echo '</div>'; //celui de tab-pane
						$j++;
					endforeach; ?>
				</div>
			</div>
		</div>
	</div>
<?php } ?>