<?php $this->headTitle()->append('Xylavie'); ?>
<div class="logo">			
	<img src="<?php echo $this->baseUrl;?>/images/bandeaux/<?php echo $this->controller;?>.jpg" alt="<?php echo $this->controller;?>">
</div>

<h1>XYLAVIE</h1>
<?php if ((count($this->first) == 0) and (count($this->else) == 0))
	echo '<h2> Nous sommes désolé mais cette page ne contient pour le moment aucun contenu, ceci devrait être rectifié d\'ici quelques jours!</h2>';
else {?>
	<div class="row">
		<div id="titreH" class="span12 ajout">
			<div class="span12 rembourse">
			<br>
			<h2><?php echo $this->first[0]->titre; ?><a onclick="_gaq.push(['_trackEvent', 'Clic sur Contact XYLAVIE', 'clic'])" href="<?php echo $this->url(array('controller'=>$this->controller,'action'=>'contact'), null, true) ?>" title="Contactez nous !"><img src="<?php echo $this->baseUrl ?>/images/contact/xylavieContact.png"></a></h2>
			<?php echo $this->first[0]->contenu;
				echo $this->partial('partials/affLoop.phtml', array('e' => $this->first[0])); ?>
			</div>
			<div class="span12 rembourse">
				<h2><?php echo $this->rbt[0]->titre; ?><a href="http://www.gmcgestion.fr" target="_blank" title="Faire une demande de devis" onclick="_gaq.push(['_trackEvent', 'Clic sur Remboursement', 'clic'])"><img src="<?php echo $this->baseUrl; ?>/images/xylavie/rbt.png"></a></h2>
				<p><?php echo $this->rbt[0]->contenu; ?></p>
				<?php if(count($this->rbt[0]->sousencad) != 0) {
					echo $this->partial('partials/affLoop.phtml', array('e' => $this->rbt[0]));
				} ?>
			</div>
			<div class="span12">
				<hr class="soften">
				<br>
			</div>






		<?php foreach ($this->nonDevis as $e): ?>
			<div class="span12" style="margin-left:0;width:100%">
			<br>
			<h2><?php echo $e->titre; ?></h2>
			<?php echo $e->contenu;?>
		<?php if (count($e->sousencad) != 0) { ?>
			<?php if (strlen($e->contenu) != 0)
				echo '<br>'; ?>
			</div>
			<div class="soustitres">
				<div class="span5">
					<div class="tabbable tabs-left">
						<ul id="tab" class="nav nav-pills nav-stacked">
							<?php $i =0;
							foreach ($e->sousencad as $s) : 
								echo ($i == 0) ? '<li class="active">' : '<li>' ; 
								echo '<a href="#'.$s->id.'" data-toggle="tab">'.$s->titre.'</a></li>';
								$i++;
							endforeach; ?>
						</ul>
					</div>
				</div>
				<div class="span7" id="alignLeft">
					<div id="myTabContent" class="tab-content">
						<?php 
						$j = 0;
						foreach ($e->sousencad as $s) : 
							echo ($j == 0) ? '<div class="tab-pane fade in active" id="'.$s->id.'">' : '<div class="tab-pane fade" id="'.$s->id.'">';
							echo $s->contenu;
							echo '</div>'; //celui de tab-pane
							$j++;
						endforeach; ?>
					</div><!--  celui de tab content -->
				</div><!--  celui de alignLeft -->					
			</div><!-- fin du div englobant les sous-titres -->
			<div class="span12">
				<hr class="soften">
			</div>
		<?php } else { echo '<hr class="soften"></div>';} ?>
		<?php endforeach ?>











			<h2 id="devis">Nos offres et nos devis</h2><br>
			<p> <span style="font-size : 1.1em; font-weight:bold;">Pour les contrats collectifs (entreprises)</span>, il est impératif de prendre contact avec nous car aucune tarification en ligne n'est envisageable.</p>
			<br>
			<p><span style="font-size : 1.1em; font-weight:bold;">Pour les particuliers</span>, cliquez sur l'onglet de votre choix.</p>
			<ul class="nav nav-pills">
				<?php $i =0;
					foreach ($this->devis as $autres) : 
						echo ($i == 0) ? '<li class="active">' : '<li>' ; 
						$lien = $autres->id + 2000;
						echo '<a href="#'.$lien.'" data-toggle="tab" title="Vous dirige vers '.$autres->titre.'">'.$autres->titre.'</a></li>';
						$i++;
					endforeach; ?>
			</ul>
			<div class="tab-content">
					<?php 
					$j = 0;
					foreach ($this->devis as $autres) : 
						$lien = $autres->id + 2000;
						$title = str_replace(array(' ','à', 'â', 'ä', 'á', 'ã', 'å','î', 'ï', 'ì', 'í', 'ô', 'ö', 'ò', 'ó', 'õ', 'ø', 'ù', 'û', 'ü', 'ú', 'é', 'è', 'ê', 'ë', 'ç', 'ÿ', 'ñ', ),
							array('', 'a', 'a', 'a', 'a', 'a', 'a', 'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u', 'u', 'e', 'e', 'e', 'e', 'c', 'y', 'n', ),$autres->titre);
						echo ($j == 0) ? '<div class="tab-pane active" id="'.$lien.'">' : '<div class="tab-pane" id="'.$lien.'">';
						echo '<div class="row">';
							echo '<div class="span12 ajout">
								<h2>'.$autres->titre.'</h2><br>';
								switch($autres->ajout) {
									case "d": echo '<a onclick="_gaq.push([\'_trackEvent\', \'Clic sur Devis '.strtoupper($autres->titre).'\', \'clic\'])" href="'.$this->url(array('controller'=>$this->controller,'action'=> 'devis'.strtolower($title).''), null, true).'" title="Faire une demande de devis"><p><img src="'.$this->baseUrl.'/images/xylavie/devis.png"></p><p class="lentite">'.$autres->titre.'</p></a>'; break;
									case "c": echo '<p><a onclick="_gaq.push([\'_trackEvent\', \'Clic sur Rensiegnements Prévoyance\', \'clic\'])" href="'.$this->url(array('controller'=>$this->controller,'action'=> strtolower($title)), null, true).'" title="Contactez nous !"><img src="'.$this->baseUrl.'/images/xylavie/contact.png"></a></p>'; break;
									default: break;
								}
								echo $autres->contenu;
								echo $this->partial('partials/affLoop.phtml', array('e' => $autres));
							echo '</div>';
						echo '</div>'; //ceklui de row
						echo '</div>'; //celui de tab-pane
						$j++;
					endforeach; ?>
				</div>
			</div>
		</div>
	</div>
<?php } ?>