<?php $this->headTitle()->append('Demande de Renseignements - Prévoyance'); ?>
<?php $this->headScript()->appendFile('/js/tinyP.js'); ?>
<div class="row" id="devis">
		<br><a id="boutonRetour" href="<?php echo $this->url(array('controller'=>'xylavie','action'=>'index'), null, true);?>" class="btn"><i class="icon-arrow-left"></i> Retour</a>
	<div class="span12" id="prevoyance">
		<h2>Demande de Renseignements - Prévoyance</h2>
		<p>Afin d'améliorer la qualité de nos réponses, tous les champs sont obligatoires.</p>
		<hr>
		<span style="margin-left: 90px;" class="label label-important">Attention</span><h4 style="display:inline;font-size:0.7em">  Veillez à être concis et ne pas faire d'erreurs dans vos coordonnées</h4>
		<form enctype="application/x-www-form-urlencoded" action="" method="post">
			<table>
				<?php echo $this->form->civ; ?>
				<?php echo $this->form->nom; ?>
				<?php echo $this->form->prenom; ?>	
				<?php echo $this->form->email; ?>	
				<?php echo $this->form->telephone; ?>	
				<?php echo $this->form->statut; ?>	
				<?php echo $this->form->demande; ?>
				<?php echo $this->form->message; ?>	
			</table>
		</form>
		<br>
		<div class="pager">
			<a href="#" id="validPrevoyance" onclick="_gaq.push(['_trackEvent', 'Clic sur Envoyer Renseignements Prévoyance', 'envoi']); return false;">Envoyer</a>
		</div>
		<p>Une fois votre demande envoyé nous ferons tout notre possible pour répondre dans les 48h.</p>
	</div>
</div>
<br>
