<?php $this->headTitle()->append('Souscription Contrat Garanties Accidents de la vie'); ?>

<br>
<h1>Souscription Devis XYLAVIE</h1>

<div class="row" id="souscription">
	<div class="span12">
		<h2 style="text-align : center; font-size: 2em">XYLAGROUP vous remercie !</h2><br>
		<h3><span class="tabul">Vous</span> venez de demander la souscription d'un contrat Garanties des Accidents de la Vie. </h3><br>
		<p>Voici un récapitulatif de ce que vous nous avez envoyé : </p>
		<?php if ($this->infos['hide'] == "carte") {?>
			<br><p class="tabul" style="color:red">Attention, pour que le paiement par prélèvement automatique se fasse correctement, vous devez IMPERATIVEMENT fournir un <span style="text-decoration:underline">RIB</span> (Relevé d'Identité Bancaire) ainsi qu'une <span style="text-decoration:underline">AUTORISATION DE PRÉLÈVEMENT</span>. <br>Si l'un de ces deux documents venait à manquer, le contrat ne pourra pas être établi.</p>
		<?php } ?>
			<h3 style="color:#FFC90E; text-decoration : underline">Les personnes assurées</h3>
			<br>
			<table class="table table-bordered table-condensed">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Prénom</th>
						<th>Date de Naissance</th>
					</tr>
				</thead>
				<tbody>
					<tr> </tr>
					<tr style="background-color : #E1E1E1">
						<td><?php echo $this->infos['nom']; ?></td>
						<td><?php echo $this->infos['prenom']; ?></td>
						<td><?php echo $this->infos['dateN']; ?></td>
					</tr>
<?php 				if($this->infos['contrat'] == "Familial") : ?>
<?php 					if($this->infos['conjoint'] == "Oui") : ?>
						<tr>
							<td><?php echo $this->infos['nomC']; ?></td>
							<td><?php echo $this->infos['prenomC']; ?></td>
							<td><?php echo $this->infos['dateC']; ?></td>
						</tr>
<?php 					endif; ?>
					<?php $nbe = $this->infos['nombreenfant']; ?>
<?php 					if($nbe != "" || $nbe != "aucun") : ?>
					<?php for ($tot = 1; $tot  <= $nbe; $tot ++) { ?>
						<tr>
							<td><?php echo $this->infos["nom".$tot]; ?></td>
							<td><?php echo $this->infos["prenom".$tot]; ?></td>
							<td><?php echo $this->infos["date".$tot]; ?></td>
						</tr>
					<?php }
				endif; ?>
<?php 				endif; ?>
				</tbody>
			</table>
			<br>
		<h3 style="color:#FFC90E; text-decoration : underline">Vos coordonnées</h3>
		<br>
		<p class="tabul">Téléphone : <span class="gras"><?php echo $this->infos['telephone']; ?></span></p>
		<p class="tabul">Email : <span class="gras"><?php echo $this->infos['email']; ?></span></p>
		<p class="tabul">Adresse : 
			<span class="gras"><?php echo $this->infos['adresse']; ?></span> - <span class="gras"><?php echo $this->infos['codeP']; ?></span> <span class="gras"><?php echo $this->infos['ville']; ?></span><br>
		</p>
		<br>

		<h3 style="color:#FFC90E; text-decoration : underline">Votre Contrat</h3>
		<br>
		<p class="tabul">Vous avez choisi un contrat <span class="gras"><?php echo strtoupper($this->infos['contrat']); ?></span></p>
		<?php if ($this->infos['hide'] == "carte") {?>
			<p class="tabul">Le moyen de paiement que vous avez choisi est <span class="gras">le prélèvement banquaire automatique MENSUEL.</span>
			<p class="tabul" style="color:green">Votre contrat GAV prendra effet immédiatement dès réception de ces deux documents.<br>
			Ainsi, un prélèvement automatique d'un montant de <span class="gras"><?php echo ($this->infos['contrat'] == "Familial") ? 20 : 11?>€</span> sera effectué chaque mois sur votre compte bancaire.<br>
			Une fois qu'il sera établi par nos services, votre contrat vous sera envoyé par voie postale.</p>
		<?php } else { ?>
			<p class="tabul">Le moyen de paiement que vous avez choisi est <span class="gras">le paiement par chèque ANNUEL.</span>
			<p class="tabul" style="color:green">Votre contrat GAV prendra effet immédiatement dès encaissement de votre chèque d'un montant de <span class="gras"><?php echo ($this->infos['contrat'] == "Familial") ? 20*12 : 11*12?>€</span>, à l'ordre de <span class="gras">XYLASSUR</span>. Votre contrat vous sera envoyé par voie postale dans les jours qui suivront.</p>
		<?php } ?>
		<br>
		<p>Nous vous remercions d'avoir choisi nos services.</p>
		<br><br>
	</div>
</div>
