 <?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<!-- Feuilles de style CSS : Bootstrap & Global -->
  <?php echo $this->headLink()->appendStylesheet('/css/second_layout.css'); ?>

</head>
<body>
	<?php echo $this->layout()->content ?>
</body>
  <?php echo $this->headScript(); ?>
</html>