<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<!-- Feuilles de style CSS : Bootstrap & Global -->
  <?php echo $this->headLink(); ?>
<!-- Fichiers jQuery pour les animations -->
  <?php echo $this->headScript(); ?>


</head>
<body>
	<div class="headerP">
		<div class="bandeau">		
			<a href="<?php echo $this->url(array('controller'=>'index',
                				 			'action'=>'index'));?>"><img src="<?php echo $this->baseUrl;?>/images/bandeau5.png" alt="Xylagroup vous conseille"></a>
		</div>
		<div class="menu">
			<ul class="navMenu">
				<li id ="one"><a <?php echo ($this->controller == "index") ? 'class="current"' : "";?> href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">ACCUEIL</a></li>

				<?php foreach (Entite::findAllExceptAccueil() as $entite) : ?>
				<li><a <?php echo (strtolower($this->controller) == strtolower($entite->nom)) ? 'class="current"' : "";?>  href="<?php echo $this->url(array(
																						'controller'=>strtolower($entite->nom),
																						'action'=>'index'));?>"><?php echo strtoupper($entite->nom);?>
					</a></li>
				<?php endforeach; ?>
			</ul> 
		</div>
	</div>
	<div class="containerP">
		<div class="content">
			<?php echo $this->layout()->content ?>
		</div>
	</div>
 	<div class="footerP">

 	</div>
</body>
</html>