<?php

/**
 * Encadre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Encadre extends BaseEncadre
{
	public function findAll() {
		return 	Doctrine_Query::create()
					->from('encadre en')
					->execute();
	}

	public function getLastOrdre($idEntity) {
		return 	Doctrine_Query::create()
					->select('MAX(en.ordre)')
					->from('Encadre en')
					->where('en.entite_id = ?', $idEntity)
					->execute();
	}

	public function findEncadreEntite($idEntity) {
		return 	Doctrine_Query::create()
					->select('en.*, s.titre')
					->from('encadre en')
					->where('en.entite_id = ?', $idEntity)
					->leftJoin('en.sousencad s') // On joint les deux tables.
					->orderBy('en.ordre ASC, s.ordre ASC')
					->execute();
	}

	public function findEncadre($idEncadre) {
		return 	Doctrine_Query::create()
					->select('en.*')
					->from('encadre en')
					->where('en.id = ?', $idEncadre)
					->execute();
	}

	public function findFirstEncadreEntite($idEntity) {
		return 	Doctrine_Query::create()
					->select('en.*, s.titre')
					->from('encadre en')
					->where('en.entite_id = ?', $idEntity)
					->andWhere('en.ordre = ?', 1)
					->leftJoin('en.sousencad s') // On joint les deux tables.
					->orderBy('en.ordre ASC, s.ordre ASC')
					->execute();
	}

	public function findEncadreNFNR($idEntity) {
		return 	Doctrine_Query::create()
					->select('en.*, s.titre')
					->from('encadre en')
					->where('en.entite_id = ?', $idEntity)
					->andWhere('en.titre != ?', 'Remboursement')
					->andWhere('en.ordre != ?', 1)
					->leftJoin('en.sousencad s') // On joint les deux tables.
					->orderBy('en.ordre ASC, s.ordre ASC')
					->execute();
	}

	public function findEncadreRbt($idEntity) {
		return 	Doctrine_Query::create()
					->select('en.*, s.titre')
					->from('encadre en')
					->where('en.entite_id = ?', $idEntity)
					->andWhere('en.titre = ?', 'Remboursement')
					->leftJoin('en.sousencad s') // On joint les deux tables.
					->orderBy('en.ordre ASC, s.ordre ASC')
					->execute();
	}

	public function updateTEncadre($newT, $id) {
		return Doctrine_Query::create()
				->update("Encadre")
				->set("titre", "?", $newT)
				->where("id = ?", $id)
				->execute();
	}

	public function updateOrdre($ordre, $idEncadre) {
		return Doctrine_Query::create()
				->update("Encadre")
				->set("ordre", "?", $ordre)
				->where("id = ?", $idEncadre)
				->execute();
	}

	public function updateEnca($titre, $contenu, $idEncadre) {
		return Doctrine_Query::create()
				->update("Encadre")
				->set("titre", "?", $titre)
				->set("contenu", "?", $contenu)
				->where("id = ?", $idEncadre)
				->execute();
	}

	public function deleteEncadre($id) {
		return Doctrine_Query::create()
				->delete('encadre e')
				->where('e.id = ?', $id)
				->execute();
	}
}