<?php

/**
 * Entite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Entite extends BaseEntite
{
	public static function findAll() {

		return Doctrine_Query::create()
					->from('entite e')
					->execute();
	}

	public static function findAllExceptAccueil() {

		return Doctrine_Query::create()
					->select('e.*')
					->from('entite e')
					->where('e.nom != ?', "ACCUEIL")
					->execute();
	}

	public function findAccueil() {

		return Doctrine_Query::create()
					->from('entite')
					->where('nom = ?', "ACCUEIL")
					->execute();
	}
}