<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews
{
	public static function findAll() {

		return Doctrine_Query::create()->from('news n')->execute();
	}

	public static function findFirstNews() {

		return Doctrine_Query::create()
					->select('n.date, n.titre, n.auteur, n.contenu')
					->from('news n')
					->where('n.date IN (SELECT MAX(ne.date) as date FROM news ne)')
					->execute();
	}

	public static function findNews($idNews) {

		return 	Doctrine_Query::create()
					->from('news n')
					->where('n.id = ?', $idNews)
					->execute();
	}
}

