<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews
{
	public static function findAll() {
		return Doctrine_Query::create()->from('news n')->execute();
	}
	public static function findAllDesc() {
		return Doctrine_Query::create()->from('news n')->orderBy('n.numero DESC')->execute();
	}
	public static function findLastNews() {
		return Doctrine_Query::create()
					->select('n.*')
					->from('news n')
					// ->where('n.date IN (SELECT MAX(ne.date) as date FROM news ne WHERE ne.visible =?)', 'oui')
					->where('n.visible = ?', 'oui')
					->orderBy('n.numero DESC')
					->execute();
	}
	public static function findNewsVisible($idNews) {
		return 	Doctrine_Query::create()
					->from('news n')
					->where('n.id = ?', $idNews)
					->andWhere('n.visible = ?', 'oui')
					->execute();
	}
	public static function findNews($idNews) {
		return 	Doctrine_Query::create()
					->from('news n')
					->where('n.id = ?', $idNews)
					->execute();
	}
	public function findPrecNews($numNews) {
		return 	Doctrine_Query::create()
					->from('news n')
					->where('n.numero < ?', $numNews)
					->andWhere('n.visible = ?', 'oui')
					->orderBy('n.numero DESC')
					->limit(0,1)
					->execute();
	}	
	public function findNextNews($numNews) {
		return 	Doctrine_Query::create()
					->from('news n')
					->where('n.numero > ?', $numNews)
					->andWhere('n.visible = ?', 'oui')
					->orderBy('n.numero ASC')
					->limit(0,1)
					->execute();
	}	
	public function newsVisible() {
		return 	Doctrine_Query::create()
					->from('news n')
					->where('n.visible =?', 'oui')
					->orderBy('n.numero DESC')
					->execute();
	}
	public function getLastNumero() {
		return Doctrine_Query::create()
					->select('MAX(n.numero)')
					->from('news n')
					->execute();
	}
	public function updateTNews($newT, $id) {
			return Doctrine_Query::create()
			->update("News")
			->set("titre", "?", $newT)
			->where("id = ?", $id)
			->execute();
	}
	public function updateNews($titre, $contenu, $idNews, $lien, $photo, $visible) {
		return Doctrine_Query::create()
				->update("News")
				->set("titre", "?", $titre)
				->set("contenu", "?", $contenu)
				->set("lien", "?", $lien)
				->set("photo", "?", $photo)
				->set("visible", "?", $visible)
				->where("id = ?", $idNews)
				->execute();
	}
	public function deleteNews($id) {
		return Doctrine_Query::create()
				->delete('news n')
				->where('n.id = ?', $id)
				->execute();
	}

}

