<?php

/**
 * Sousencadre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sousencadre extends BaseSousencadre
{
	public function findSousEncadre($idSousencadre) {
		return 	Doctrine_Query::create()
					->from('Sousencadre se')
					->where('se.id = ?', $idSousencadre)
					->execute();
	}
	public function getLastOrdre($idSEncadre) {
		return 	Doctrine_Query::create()
					->select('MAX(se.ordre)')
					->from('sousencadre se')
					->where('se.encadre_id = ?', $idSEncadre)
					->execute();
	}
	public function deleteFromEncadre($idEncadre) {
		return Doctrine_Query::create()
					->delete('Sousencadre s')
					->where('s.encadre_id = ?', $idEncadre)
					->execute();
	}
	public function findSousencadEncad($idEncadre) {
		return 	Doctrine_Query::create()
					->select('se.*')
					->from('sousencadre se')
					->where('se.encadre_id = ?', $idEncadre)
					->orderBy('se.ordre ASC')
					->execute();
	}
	public function updateTsousencadre($newT, $id) {
		return Doctrine_Query::create()
				->update("Sousencadre")
				->set("titre", "?", $newT)
				->where("id = ?", $id)
				->execute();
	}
	public function updateOrdre($ordre, $idSousencadre) {
		return Doctrine_Query::create()
				->update("sousencadre")
				->set("ordre", "?", $ordre)
				->where("id = ?", $idSousencadre)
				->execute();
	}
	public function updateSousEnca($titre, $contenu, $idSousencadre, $visible) {
		return Doctrine_Query::create()
				->update("Sousencadre")
				->set("titre", "?", $titre)
				->set("contenu", "?", $contenu)
				->set("visible", "?", $visible)
				->where("id = ?", $idSousencadre)
				->execute();
	}
	public function deleteSousencadre($id) {
		return Doctrine_Query::create()
				->delete('sousencadre se')
				->where('se.id = ?', $id)
				->execute();
	}
}