<?php

/**
 * Sousencadre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sousencadre extends BaseSousencadre
{
	public function findSEEncadre($idEncadre) {

		return 	Doctrine_Query::create()
					->from('Sousencadre se')
					->where('se.encadre_id = ?', $idEncadre)
					->orderBy('en.ordre ASC')
					->execute();

	}

	public function deleteFromEncadre($idEncadre) {

		return Doctrine_Query::create()
					->delete('Sousencadre s')
					->where('s.encadre_id = ?', $idEncadre)
					->execute();
	}
}