<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Users extends BaseUsers
{
	const PAS_TROUVE = 1;
	const MAUVAIS_PASS  = 2;

	public static function authenticate($username, $password)
	{
		$user = Doctrine_Core::getTable('Users')->findOneByUsername($username);
		if ($user) 
		{
			if ($user->password == $password)
				return $user;

			throw new Exception(self::MAUVAIS_PASS);
		}
		throw new Exception(self::PAS_TROUVE);
	}

	public function trouve()
	{
		return Doctrine_Query::create()->from('Users u')->execute();
	}
}