<?php $this->headTitle()->append('Administration'); ?>
<br><br>
<div class="row">
	<div class="span12">
		<h2>Avertissements du Webmaster</h2><br>
		<p style="color:white">Vous êtes actuellement sur l'espace reservé à l'administration du site <span style="text-decoration:underline">www.xylagroup.fr</span>, suivant vos droits vous pouvez <span style="color:#C90;"><strong>modifier</strong></span>, <span style="color:#C90;"><strong>ajouter</strong></span> ou même <span style="color:#C90;"><strong>supprimer</strong></span> du contenu. Or, toute <span style="color:#C90;">mise en ligne</span> necessite l'approbation d'un des associés, ainsi tout ce que vous modifierez ou ajouterez <span style="color:#C90;">ne sera pas en ligne tant qu'un associé ne l'aura pas validé</span>.<br><br>
		<span style="text-decoration:underline">Voici quelques règles à suivre pour bien utiliser cette partie administration :</span><br><br>
		<span style="margin-left:15px">-</span> Avant toute chose, il est nécessaire que le Javascript soit activé sur votre navigateur (il est activé par défaut).<br><br>
		<span style="margin-left:15px">-</span> Si vous modifiez le contenu de la page d'ACCUEIL, vous remarquerez que le contenu de "News" ne peut être modifié, cela est normal, vous pouvez uniquement modifier le <span style="color:#09F;">TITRE</span>.<br><br>
		<span style="margin-left:15px">-</span> Lorsque vous cliquez sur <a class="btn btn-primary btn-mini" title="Modifier ce Titre"><i style="margin:3px 4px 1px 1px" class="icon-white icon-pencil"></i>modifier le titre</a> ou <a class="btn btn-mini btn-danger" title="Supprimer ce Titre"><i style="margin:3px 4px 1px 1px" class="icon-white icon-remove"></i>supprimer</a>, la validation ne peut se faire par la touche "Entrée", il est nécessaire de cliquer sur un des boutons présents dans la fenêtre qui s'est ouverte.<br><br>
		<span style="margin-left:15px"></span>- Pour modifier l'ordre d'affichage des <span style="color:#09F;">TITRES</span>/<span style="color:#090;">SOUS-TITRES</span> il vous suffit de cliquer sur <a title="Modifier l'ordre pour" class="btn btn-warning couleurNoire"><i class="icon-wrench"></i>Modifier l'ordre</a> et de faire glisser les titres à la place que vous souhaitez.<br><br>
		<span style="margin-left:15px"></span>- <span style="color:red"><u>ATTENTION</u> </span>: Pour l'entité XYLAVIE, il est fortement déconseillé de modifier l'ordre des <span style="color:#09F;">DEUX PREMIERS TITRES</span> !<br><br>
		<span style="margin-left:15px">-</span> Enfin, chaque texte dispose d'un état "visible", cet état est à "non" par défaut et ne peut être modifié uniquement par les associés. Ainsi, tout le monde peut ajouter ou modifier du contenu, mais <span style="color:white">il est nécessaire que celui-ci soit validé par un des associés.</span></p><br>
		<h4><u>Exemple (survolez les boutons pour connaître leur utilité) :</u></h4>
		<br>
		<table class="table table-bordered" id="tabNoir">
			<thead><tr><th>Grand titre</th><th>Actions</th><th>Visible</th><th>Ordre</th></tr></thead>
			<tbody>
				<tr>
					<td class="tdGrey"><a class="pop" data-content="En cliquant sur ce lien, vous accédez à l'interface de modification du Titre" rel="popover" href="#" data-original-title="Edition du titre" href="#">Un Grand titre</a></td>
					<td class="tdLeft">
						<a class="btn btn-primary btn-mini pop" data-content="En cliquant sur ce lien, un fenêtre s'ouvre pour modifier le libellé du Titre" rel="popover" href="#" data-original-title="Modification du titre"><i style="margin:3px 4px 1px 1px" class="icon-white icon-pencil"></i>modifier le titre</a>
						<a class="btn btn-mini btn-danger pop" data-content="En cliquant sur ce lien, un fenêtre s'ouvre pour supprimer le Titre ainsi que ses Sous-titres" rel="popover" href="#" data-original-title="Supprression du titre"><i style="margin:3px 4px 1px 1px" class="icon-white icon-remove"></i>supprimer</a>
						<a href="" class="btn btn-info btn-mini couleurNoire pop" data-content="En cliquant sur ce lien, vous accédez aux Sous-titres relatifs à ce Titre" rel="popover" href="#" data-original-title="Sous-titres du titre"><i class="icon-share-alt"></i>Voir les Sous-titres</a>
					</td>
					<td class="tdGrey">non</td>
					<td class="tdGrey">1</td>
				</tr>
				<tr>
					<td class="tdGrey"><a title="Modifier le contenu du titre" href="#">Un Second Grand titre</a></td>
					<td class="tdLeft">
						<a class="btn btn-primary btn-mini pop" data-content="En cliquant sur ce lien, un fenêtre s'ouvre pour modifier le libellé du Titre" rel="popover" href="#" data-original-title="Modification du titre"><i style="margin:3px 4px 1px 1px" class="icon-white icon-pencil"></i>modifier le titre</a>
						<a class="btn btn-mini btn-danger pop" data-content="En cliquant sur ce lien, un fenêtre s'ouvre pour supprimer le Titre ainsi que ses Sous-titres" rel="popover" href="#" data-original-title="Suppression du titre"><i style="margin:3px 4px 1px 1px" class="icon-white icon-remove"></i>supprimer</a>
						<a href="#" class="btn btn-success btn-mini couleurNoire pop" data-content="En cliquant sur ce lien, vous accédez à l'interface d'ajout d'un Sous-titre à ce Titre" rel="popover" data-original-title="Ajout d'un Sous-titre au titre"><i class="icon-plus-sign"></i>Ajouter un Sous-titre</a>
					</td>
					<td class="tdGrey">oui</td>
					<td class="tdGrey">2</td>
				</tr>
			</tbody>
		</table>
		<p style="color:white">Tout est dit, c'est à vous de jouer, et surtout n'hésitez pas à me rapporter le moindre soucis.</p><br>
		<p style="font-weight:bold">Pierre Julien</p>
	</div>
</div>