<?php $this->headTitle()->append('Administration'); ?>
<br><br>
<div class="row">
	<div class="span12">
		<h2>Avertissements du Webmaster</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut neque erat, mattis in sagittis a, porta ac ante. Praesent quis nisi ac est pulvinar rhoncus eu eu risus. Sed molestie, lorem a varius vehicula, ligula velit elementum quam, ut bibendum erat tortor vel mauris. Sed ipsum risus, mattis vitae blandit vel, varius in nulla. Nulla eleifend dignissim massa at adipiscing. Fusce in elit leo. Pellentesque risus odio, consequat eget feugiat id, vehicula nec tellus.

		Cras quis libero et lorem aliquet mattis a et dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus mattis malesuada. Quisque sapien dui, pulvinar dignissim hendrerit vel, euismod laoreet tortor. Duis facilisis nulla a justo tristique in dapibus sapien auctor. Suspendisse mollis, orci ac volutpat tincidunt, lectus arcu adipiscing enim, et aliquam odio augue quis velit. Integer nisi elit, cursus vitae placerat id, dictum non leo.

		Vivamus justo libero, fermentum sed semper a, luctus quis metus. Donec dignissim, magna sed interdum congue, mi eros hendrerit odio, mollis vulputate eros nulla ac nisl. Nunc consectetur sem purus. Aenean eu scelerisque neque. Duis neque massa, fermentum a condimentum sit amet, tincidunt ut augue. Donec sed ligula metus. Nulla vitae odio orci, vel dapibus sapien. Nunc faucibus orci et nulla placerat accumsan. Proin in ligula in metus mollis pellentesque ut id dui. Duis adipiscing, lorem id iaculis consequat, felis velit pharetra nunc, at posuere nisi velit convallis mi. Pellentesque dictum, dui non tincidunt tempor, sem felis tincidunt nunc, sed auctor justo ante quis libero. Nullam bibendum nunc in ligula tincidunt euismod. In mi nunc, egestas non lacinia quis, ornare vel magna. Donec tortor mauris, mollis ornare bibendum at, egestas eu tellus.

		Curabitur vel neque eros, vel tempus mi. Cras dictum mollis massa, in posuere erat ornare quis. Donec consequat malesuada velit bibendum blandit. Aenean eu diam sapien. Praesent euismod dignissim lorem, id congue lectus tincidunt vitae. Duis facilisis ullamcorper est, fringilla auctor nisl dignissim et. Aenean venenatis, erat quis pretium faucibus, urna nibh pharetra odio, sit amet rutrum mi lectus sed mi. Sed nisi lectus, sodales ut pretium a, facilisis in ipsum.

		Nulla posuere arcu porttitor nunc rhoncus ut adipiscing mi consectetur. Donec purus odio, venenatis eget accumsan eu, cursus nec elit. Duis mattis posuere quam vel pellentesque. Morbi ornare magna nec enim condimentum eget vehicula neque dictum. Curabitur magna quam, tincidunt eget condimentum non, aliquet eu velit. Etiam tempus arcu nec tellus pretium eu fringilla elit pulvinar. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ullamcorper bibendum dignissim. Integer malesuada sodales tellus. Aliquam eget ultricies enim. Nulla commodo metus vitae mi ultricies vestibulum. Fusce mollis, elit a consectetur cursus, neque est bibendum massa, bibendum luctus eros dui in neque. Quisque imperdiet semper augue, vitae rhoncus purus pellentesque ut. Sed viverra imperdiet velit, vitae posuere quam porttitor at. </p>

		Par exemple pour < news> qu'il ne faut pas enlever	
	</div>
</div>