<?php $this->headTitle()->append('Erreur - Page introuvable'); ?>
<div class="row">
	<div id="titreH" class="span12 ajout">
			<h1>Erreur XYLAGROUP</h1>
		<br>
			<img src="<?php $this->baseUrl; ?>/images/using/404.png" alt="" style="float:left">
		<br><br><br><br><br><br>
			<p>Attention, la page que vous avez demandé est introuvable. <br>Si vous pensez que cette page devrait exister, n'hésitez pas à le signaler en <a href="<?php echo $this->url(array('controller'=>'pages','action'=>'bug'), null, true);?>" title="Signaler une erreur">contactant le webmaster</a>.</p>
		<hr>
			<p>Maintenant que vous êtes arrivés jusqu'ici, autant que cela vous soit bénéfique :</p>
		<br>
			<h3><u>Chapitre :</u> <span style="color: #EA0"><?php echo $this->article->chapitre; ?></span></h3>
		<br>
			<h4>Code des Assurances Article <?php echo $this->article->numero; ?></h4>
			<p>"<?php echo $this->article->contenu; ?>"</p>
			<p>Source : <a href="http://www.legifrance.gouv.fr" title="LegiFrance">www.legifrance.gouv.fr/</a></p>
		<hr>
		<br>
			<p>N'hésitez pas à nous contacter pour toute information, en allant sur la page de l'entité qui vous interesse. Vous pouvez également souscrire un devis <a href="<?php echo $this->url(array('controller'=>'xylavie','action'=>'index'), null, true);?>" title="Devis">par ici</a>.</p>
		<br>
			<p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'), null, true);?>" title="Menu principal">Cliquez ici</a> pour revenir au menu principal.</p>
	</div>
</div>
<?php //echo $this->today; ?>
<?php //echo var_dump($this->today); ?>