<?php $this->headTitle()->append('Administration - '.strtoupper($this->controller)); ?>
<?php $this->headScript()->appendFile('/js/verifchamps.js'); ?>
<br><br>
<div class="row">
	<div class="span12">
		<h2><?php echo strtoupper($this->controller); ?> - Modifications</h2><br>

		<a href="<?php echo $this->url(array('controller'=> $this->controller,'action'=>'ajouter'), null, true);?>"
		     title="Ajouter un titre pour <?php echo $this->controller; ?>"><button class="btn btn-success">Ajouter</button></a>
		&nbsp;
		<a href="<?php echo $this->url(array('controller'=> $this->controller,'action'=>'ordre'), null, true);?>"
		     title="Ajouter un titre pour <?php echo $this->controller; ?>"><button class="btn btn-warning">Modifier l'ordre</button></a>
		<br><br>
		<table class="table table-bordered">
			<thead style="background-color:white; color:black">
				<tr>
					<th>Grand titre</th>
					<th>Actions</th>
					<th>Ordre</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->encadres as $en): ?>				
				<tr>
					<td><?php echo $en->titre; ?></td>
					<td>
						<a class="btn btn-mini btn-primary" id="edit" href="#myModal" data-id="<?php echo $en->id; ?>" data-titre="<?php echo $en->titre; ?>" title="Modifier ce Titre" data-toggle="modal">modifier</a>&nbsp;&nbsp;
						<a class="btn btn-mini btn-danger" href="#deleteModal" title="Supprimer ce Titre" data-toggle="modal">supprimer</a>
					</td>
					<td><?php echo $en->ordre; ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div id="myModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Modifier le titre d'un encadre</h3>
		</div>
		<div class="modal-body">
			<input type="hidden" name="id" value="">
			<input type="text" name="titre" value="">
		</div>
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input class="btn btn-primary" type="submit" value="Sauvegarder" >
		</div>
	</form>
</div>

<div id="deleteModal" class="modal hide fade" style="display: none;">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		<h3>Suppression d'un titre</h3>
	</div>
	<div class="modal-body">
		<img src="<?php echo $this->baseUrl;?>/images/using/attention.png" alt="Attention !"><p id="q">Êtes-vous sûr de vouloir supprimer ce titre ?</p><br><p style="color:red">(Attention, cela supprimera également tous les sous-titres relatifs à ce titre!)</p>
	</div>
	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" href="#">Non</a>
		<a class="btn btn-primary" data-dismiss="modal" href="<?php echo $this->url(array('controller'=> $this->controller, 'action'=>'supp'), null, true);?>">Oui</a>
	</div>
</div>