<?php $this->headTitle()->append('Administration - '.strtoupper($this->controller)); ?>
<?php $this->headScript()->appendFile('/js/verifchamps.js'); ?>
<br><br>
<div class="row">
	<div class="span12">
		<h2><?php echo strtoupper($this->controller); ?> - Modifications</h2><br>

		<a href="<?php echo $this->url(array('controller'=> $this->controller,'action'=>'ajouter'), null, true);?>"
		     title="Ajouter un titre pour <?php echo $this->controller; ?>"><button class="btn btn-success"><i class="icon-white icon-plus"></i>Ajouter</button></a>
		&nbsp;
		<a href="#ordreModal"  data-toggle="modal" title="Ajouter un titre pour <?php echo $this->controller; ?>"><button class="btn btn-warning"><i class="icon-white icon-wrench"></i>Modifier l'ordre</button></a>
		<br><br>
		<table class="table table-bordered">
			<thead style="background-color:white; color:black">
				<tr>
					<th>Grand titre</th>
					<th>Actions</th>
					<th>Ordre</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->encadres as $en): ?>				
				<tr>
					<td><?php echo $en->titre; ?></td>
					<td>
						<a class="btn btn-primary btn-mini" id="edit" href="#myModal" data-id="<?php echo $en->id; ?>" data-titre="<?php echo $en->titre; ?>" title="Modifier ce Titre" data-toggle="modal"><i style="margin:3px 4px 1px 1px"class="icon-white icon-pencil"></i>modifier</a>&nbsp;&nbsp;
						<a class="btn btn-mini btn-danger" id="delete" href="#deleteModal" title="Supprimer ce Titre" data-toggle="modal" data-id="<?php echo $en->id; ?>" ><i style="margin:3px 4px 1px 1px"class="icon-white icon-remove"></i>supprimer</a>
					</td>
					<td><?php echo $en->ordre; ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div id="ordreModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Modifier l'ordre des encadres</h3>
		</div>
		<div class="modal-body">
			<ul id="sortable">
				<?php $i = 1; ?>
				<?php foreach ($this->encadres as $en): ?>
					<li id="<?php echo $en->id; ?>" class="ui-state-default"><?php echo $en->titre; ?> <input type="hidden" class="<?php echo $en->id; ?>" id="<?php echo $i; ?>" name="<?php echo $i; ?>" value="" ></li>
					<?php $i++; ?>
				<?php endforeach; ?>
			</ul>
		</div>
		<input type="hidden" name="nombre" value="<?php echo count($this->encadres); ?>">
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input name="send" class="btn btn-primary" type="submit" value="Ordonner">
		</div>
	</form>
</div>

<div id="myModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Modifier le titre d'un encadre</h3>
		</div>
		<div class="modal-body">
			<input type="hidden" name="id" value="">
			<input type="text" name="titre" value="">
		</div>
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input name="send" class="btn btn-primary" type="submit" value="Sauvegarder">
		</div>
	</form>
</div>

<div id="deleteModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Suppression d'un titre</h3>
		</div>
		<div class="modal-body">
			<img src="<?php echo $this->baseUrl;?>/images/using/attention.png" alt="Attention !"><p id="q">Êtes-vous sûr de vouloir supprimer ce titre ?</p><br><p style="color:red">(Attention, cela supprimera également tous les sous-titres relatifs à ce titre!)</p>
			<input type="hidden" name="id_del" value="">
		</div>
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input name="send" class="btn btn-primary" type="submit" value="Supprimer">
		</div>
	</form>
</div>