<?php if($this->controller == "index") {
	$this->headTitle()->append('Administration - ACCUEIL');
} else {
	$this->headTitle()->append('Administration -  '.strtoupper($this->controller));
} ?>
<?php $this->headScript()->appendFile('/js/verifchamps.js'); ?>
<br>
<a style="margin-left:35px" href="<?php echo $this->url(array('controller'=> $this->controller,'action'=>'modif'), null, true);?>" title="Retour aux menu de modifications" class="btn"><i class="icon-arrow-left"></i>Menu des Titres</a><br>
<div class="row">
	<div class="span12">
		<h2>Modifications - Sous-Titres de "<?php echo $this->titre[0]->titre; ?>"</h2><br>
		<a href="<?php echo $this->url(array('controller'=> $this->controller,'action'=>'ajouterst', 'id' => $this->titre[0]->id), null, true);?>"
		     title="Ajouter un sous-titre pour <?php echo ($this->controller == "index") ? "ACCUEIL" : strtoupper($this->controller); ?>" class="btn btn-success"><i class="icon-white icon-plus"></i>Ajouter</a>
		&nbsp;
		<a href="#ordreModal"  data-toggle="modal" title="Ajouter un titre pour <?php echo ($this->controller == "index") ? "ACCUEIL" : strtoupper($this->controller); ?>" class="btn btn-warning"><i class="icon-white icon-wrench"></i>Modifier l'ordre</a>
		<br><br>
		<table class="table table-bordered">
			<thead style="background-color:white; color:black">
				<tr>
					<th>Sous titre</th>
					<th>Actions</th>
					<th>Ordre</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->soustitres as $se): ?>				
				<tr>
					<td><a href="<?php echo $this->url(array('controller'=> $this->controller,'action'=>'editSE','id' => $se->id), null, true);?>"><?php echo $se->titre; ?></a></td>
					<td style="text-align:left; padding-left:14%;">
						<a class="btn btn-primary btn-mini" id="edit" href="#myModal" data-id="<?php echo $se->id; ?>" data-titre="<?php echo $se->titre; ?>" title="Modifier ce Titre" data-toggle="modal"><i style="margin:3px 4px 1px 1px" class="icon-white icon-pencil"></i>modifier le titre</a>
						<a class="btn btn-mini btn-danger" id="delete" href="#deleteModal" title="Supprimer ce Titre" data-toggle="modal" data-id="<?php echo $se->id; ?>" ><i style="margin:3px 4px 1px 1px" class="icon-white icon-remove"></i>supprimer</a>
					</td>
					<td><?php echo $se->ordre; ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div id="ordreModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Modifier l'ordre des encadres</h3>
		</div>
		<div class="modal-body">
			<ul id="sortable">
				<?php $i = 1; ?>
				<?php foreach ($this->soustitres as $se): ?>
					<li id="<?php echo $se->id; ?>" class="ui-state-default"><?php echo $se->titre; ?><input id="<?php echo $i; ?>" type="hidden" name="<?php echo $se->id; ?>" value="" ></li>
					<?php $i++; ?>
				<?php endforeach; ?>
			</ul>
		</div>
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input name="send" class="btn btn-primary" type="submit" value="Ordonner">
		</div>
	</form>
</div>

<div id="myModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Modifier un Titre et son Contenu</h3>
		</div>
		<div class="modal-body">
			<input type="hidden" name="id" value="">
			<input type="text" name="titre" value="">
		</div>
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input name="send" class="btn btn-primary" type="submit" value="Sauvegarder">
		</div>
	</form>
</div>

<div id="deleteModal" class="modal hide fade" style="display: none;">
	<form action="" method="post">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">×</button>
			<h3>Suppression d'un titre</h3>
		</div>
		<div class="modal-body">
			<img src="<?php echo $this->baseUrl;?>/images/using/attention.png" alt="Attention !"><p id="q">Êtes-vous sûr de vouloir supprimer ce sous-titre ?</p><br><p style="color:red">(Ce choix sera irréversible!)</p>
			<input type="hidden" name="id_del" value="">
		</div>
		<div class="modal-footer">
			<a class="btn" data-dismiss="modal" href="#">Annuler</a>
			<input name="send" class="btn btn-primary" type="submit" value="Supprimer">
		</div>
	</form>
</div>