<body>
<p>Bonjour <?php echo $this->civilite; ?> <?php echo $this->nom; ?>, <br><br>Nous vous informons qu'en date du <span style="font-weight:bold"><?php echo $this->date; ?></span>, la société <?php echo $this->controller; ?> a bien reçu une demande de devis <span style="font-weight:bold">Garanties des Accidents de la vie</span> de votre part.<br><br>
	<span style="color:red; text-decoration:underline">Attention :</span><br>
<?php if($this->hide !="carte") { ?>
	Nous vous rappelons qu'afin de valider votre souscription de contrat, vous devez envoyer un <span style="font-weight:bold">chèque d'un montant de <?php echo ($this->contrat == "familial") ? "240€" : "132€"; ?></span> à l'ordre de <span style="font-weight:bold">XYLASSUR</span>, à l'adresse suivante : <br><span style="font-weight:bold"><br>
	Société XYLASSUR <br>
	3 Chemin de Parenty <br>
	69250 Neuville sur Saône</span>
<?php } else { ?>
	Nous vous rappelons qu'afin de valider votre souscription de contrat, vous devez envoyer un <span style="font-weight:bold">RIB</span> et une <span style="font-weight:bold">autorisation de prélèvement</span> à l'adresse suivante :  <br><br><span style="font-weight:bold">
	Société XYLASSUR <br>
	3 Chemin de Parenty <br>
	69250 Neuville sur Saône</span>
<?php } ?>
<br><br>
	Nous mettons tout en oeuvre pour répondre au plus vite à votre demande.<br><br>Cordialement,<br><br><?php echo $this->controller; ?></p>
<p style="margin:0 0 0 0; padding-bottom: 5px; font-size: 0.8em; border-bottom: 2px solid #e0e0e0;"><span style="margin-left:10px;">Ceci est un email automatique, merci de ne pas y répondre.</span></p>
<p style="margin: 5px 0 0 10px;"><a style="text-decoration:none;  font-weight:bold; " href="http://www.xylagroup.fr"><span style="color:#9ebad1;">www.</span><span style="color:#4c657d;">xylagroup</span><span style="color:#9ebad1;">.fr</span></a></p>
<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo $this->controller; ?> SARL au capital de 50 000 € / 492 320 320 Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07007951 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
</body>