<body>
<p>Bonjour, <br><br>En date du <span style="font-weight:bold"><?php echo $this->date; ?></span>, la société <?php echo strtoupper($this->infos['controller']); ?> a reçu un message de la part de <span style="font-weight:bold"><?php echo $this->infos['civilite']; ?> <?php echo $this->infos['nom']; ?></span><br><br>Voici son message : </p><?php echo $this->infos['message']; ?><br></p>Ses coordonnées sont les suivantes : <br>Email : <?php echo $this->infos['email']; ?><br>Tel : <?php echo $this->infos['telephone']; ?><br><br>Bonne journée<p>
<p style="margin:0 0 0 0; padding-bottom: 5px; font-size: 0.8em; border-bottom: 2px solid #e0e0e0;"><span style="margin-left:10px;">Ceci est un email automatique, merci de ne pas y répondre.</span></p>
<p style="margin: 5px 0 0 10px;"><a style="text-decoration:none;  font-weight:bold; " href="http://www.xylagroup.fr"><span style="color:#9ebad1;">www.</span><span style="color:#4c657d;">xylagroup</span><span style="color:#9ebad1;">.fr</span></a></p>
<?php if($this->infos['controller'] == "xylassur") {?>
	<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo strtoupper($this->infos['controller']); ?> SARL au capital de 430 000 € / 433 301 256 RCS Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07001095 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
<?php } else if($this->infos['controller'] == "xylavie") {?>
	<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo strtoupper($this->infos['controller']); ?> SARL au capital de 50 000 € / 492 320 320 Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07007951 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
<?php } else if($this->infos['controller'] == "xylabtp") {?>
	<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo strtoupper($this->infos['controller']); ?> SARL au capital de 87 500 € / 441 620 770 RCS Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07005988 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
<?php } else if($this->infos['controller'] == "xylarisk") {?>
	<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo strtoupper($this->infos['controller']); ?></p>
<?php } ?>
</body>