<body>
<p>Bonjour, <br><br>En date du <span style="font-weight:bold"><?php echo $this->date; ?></span>, la société <?php echo strtoupper($this->infos['controller']); ?> a reçu une demande de devis <strong>Dépendance</strong>.
<br>
<br>
Voici les informations relatives au demandeur <?php if($this->infos['conjoint'] == "Oui") {echo 'ainsi que celles de '; echo ($this->infos['civC'] == "Mme." || $this->infos['civC'] == "Mlle.") ? "sa conjointe " : "son conjoint ";}?> :
<br>
<span style="font-weight:bold"><?php echo $this->infos['civ']; ?> <?php echo $this->infos['nom']; ?> <?php echo $this->infos['prenom']; ?></span>, qui est le demandeur, est né<?php echo ($this->infos['civ'] == "Mme." || $this->infos['civ'] == "Mlle.") ? "e" : "";?> le <span style="font-weight:bold"><?php echo $this->infos['dateN']; ?></span><?php if($this->infos['conjoint'] == "Oui") {echo ' et <span style="font-weight:bold">'.$this->infos['civC'].' '.$this->infos['nomC'].' '.$this->infos['prenomC'].'</span>, '; echo ($this->infos['civC'] == "Mme." || $this->infos['civC'] == "Mlle.") ? "sa conjointe, est née" : "son conjoint, est né"; echo ' le <span style="font-weight:bold">'.$this->infos['dateC'].'</span>';}?>.<br><br> L'adresse relative à la demande est : <br>
<span style="font-weight:bold"><?php echo $this->infos['adresse']; ?></span><br>
<span style="font-weight:bold"><?php echo $this->infos['codeP']; ?> <?php echo $this->infos['ville']; ?></span>
<br><br>
Son adresse e-mail est <?php echo $this->infos['email']; ?> et son numéro de téléphone est le <span style="font-weight:bold"><?php echo $this->infos['telephone']; ?></span>
<br>
Cette personne dispose d'une  <span style="font-weight:bold">rente de <?php echo $this->infos['rente']; ?></span>,  <span style="font-weight:bold"><?php echo ($this->infos['depT'] == "Oui") ? "souhaite" : "ne souhaite pas";?></span> une dépendance totale, et  <span style="font-weight:bold"><?php echo ($this->infos['depTP'] == "Oui") ? "souhaite" : "ne souhaite pas";?></span> une dépendance totale ou partielle.<br><br>Bonne journée</p>
<p style="margin:0 0 0 0; padding-bottom: 5px; font-size: 0.8em; border-bottom: 2px solid #e0e0e0;"><span style="margin-left:10px;">Ceci est un email automatique, merci de ne pas y répondre.</span></p>
<p style="margin: 5px 0 0 10px;"><a style="text-decoration:none;  font-weight:bold; " href="http://www.xylagroup.fr"><span style="color:#9ebad1;">www.</span><span style="color:#4c657d;">xylagroup</span><span style="color:#9ebad1;">.fr</span></a></p>
<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo strtoupper($this->infos['controller']); ?> SARL au capital de 50 000 € / 492 320 320 Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07007951 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
</body>