<body>
<p>Bonjour, <br><br>En date du <span style="font-weight:bold"><?php echo $this->date; ?></span>, la société <?php echo strtoupper($this->infos['controller']); ?> a reçu une demande de devis <strong>GAV</strong>.
<br>
<br>
Voici les informations relatives à la demande :
<br>
Le demandeur est <span style="font-weight:bold"><?php echo $this->infos['civ']; ?> <?php echo $this->infos['nom']; ?> <?php echo $this->infos['prenom']; ?></span>.
<p style="color:#F60; text-decoration : underline">Les personnes assurées</p>
<br>
<p style="margin-left : 30px">- <?php echo $this->infos['civ']; ?> <?php echo $this->infos['nom']; ?> <?php echo $this->infos['prenom']; ?>, né<?php echo ($this->infos['civ'] == "Mme." || $this->infos['civ'] == "Mlle.") ? "e" : "";?> le <span style="font-weight:bold"><?php echo $this->infos['dateN']; ?></span></p>
<?php 	if($this->infos['contrat'] == "Familial") : ?>
	<?php 	if($this->infos['conjoint'] == "Oui") : ?>
		<p style="margin-left : 30px; text-decoration : underline; font-weight:bold"><?php echo ($this->infos['civC'] == "Mme." || $this->infos['civC'] == "Mlle.") ? "La conjointe :" : "Le conjoint :";?></p><p style="margin-left : 30px;">- <?php echo $this->infos['civC']; ?> <?php echo $this->infos['nomC']; ?> <?php echo $this->infos['prenomC']; ?>, né<?php echo ($this->infos['civC'] == "Mme." || $this->infos['civC'] == "Mlle.") ? "e" : "";?> le <span style="font-weight:bold"><?php echo $this->infos['dateC']; ?></span></p>
	<?php 	endif; ?>
	<?php $nbe = $this->infos['nombreenfant']; ?>
	<?php 	if($this->infos['nombreenfant'] == 1) { 
			echo '<p style="margin-left : 30px; text-decoration : underline; font-weight:bold">L\'enfant :</p>';
			echo '<p style="margin-left : 30px">- '.$this->infos['nom1'].' '.$this->infos['prenom1'].' né(e) le <span style="font-weight:bold">'.$this->infos['date1'].'</span></p><br>';
		} elseif ($this->infos['nombreenfant'] == 2) {
			echo '<p style="margin-left : 30px; text-decoration : underline; font-weight:bold">Les enfants :</p>';
			echo '<p style="margin-left : 30px">- '.$this->infos['nom1'].' '.$this->infos['prenom1'].' né(e) le <span style="font-weight:bold">'.$this->infos['date1'].'</span><br>';
			echo '- '.$this->infos['nom2'].' '.$this->infos['prenom2'].' né(e) le <span style="font-weight:bold">'.$this->infos['date2'].'</span></p><br>';
		} elseif ($this->infos['nombreenfant'] == 3) {
			echo '<p style="margin-left : 30px; text-decoration : underline; font-weight:bold">Les enfants :</p>';
			echo '<p style="margin-left : 30px">- '.$this->infos['nom1'].' '.$this->infos['prenom1'].' né(e) le <span style="font-weight:bold">'.$this->infos['date1'].'</span><br>';
			echo '- '.$this->infos['nom2'].' '.$this->infos['prenom2'].' né(e) le <span style="font-weight:bold">'.$this->infos['date2'].'</span><br>';
			echo '- '.$this->infos['nom3'].' '.$this->infos['prenom3'].' né(e) le <span style="font-weight:bold">'.$this->infos['date3'].'</span></p><br>';
		} elseif ($this->infos['nombreenfant'] == 4) {
			echo '<p style="margin-left : 30px; text-decoration : underline; font-weight:bold">Les enfants :</p>';
			echo '<p style="margin-left : 30px">- '.$this->infos['nom1'].' '.$this->infos['prenom1'].' né(e) le <span style="font-weight:bold">'.$this->infos['date1'].'</span><br>';
			echo '- '.$this->infos['nom2'].' '.$this->infos['prenom2'].' né(e) le <span style="font-weight:bold">'.$this->infos['date2'].'</span><br>';
			echo '- '.$this->infos['nom3'].' '.$this->infos['prenom3'].' né(e) le <span style="font-weight:bold">'.$this->infos['date3'].'</span><br>';
			echo '- '.$this->infos['nom4'].' '.$this->infos['prenom4'].' né(e) le <span style="font-weight:bold">'.$this->infos['date4'].'</span></p><br>';
		} elseif ($this->infos['nombreenfant'] == 5) {
			echo '<p style="margin-left : 30px; text-decoration : underline; font-weight:bold">Les enfants :</p>';
			echo '<p style="margin-left : 30px">- '.$this->infos['nom1'].' '.$this->infos['prenom1'].' né(e) le <span style="font-weight:bold">'.$this->infos['date1'].'</span><br>';
			echo '- '.$this->infos['nom2'].' '.$this->infos['prenom2'].' né(e) le <span style="font-weight:bold">'.$this->infos['date2'].'</span><br>';
			echo '- '.$this->infos['nom3'].' '.$this->infos['prenom3'].' né(e) le <span style="font-weight:bold">'.$this->infos['date3'].'</span><br>';
			echo '- '.$this->infos['nom4'].' '.$this->infos['prenom4'].' né(e) le <span style="font-weight:bold">'.$this->infos['date4'].'</span><br>';
			echo '- '.$this->infos['nom5'].' '.$this->infos['prenom5'].' né(e) le <span style="font-weight:bold">'.$this->infos['date5'].'</span></p><br>';
		}?>
<?php 	endif; ?>
<br>
<p style="color:#F60; text-decoration : underline">Les coordonnées</p>
<br>
<p style="margin-left : 30px">Téléphone : <span style="font-weight : bold"><?php echo $this->infos['telephone']; ?></span></p>
<p style="margin-left : 30px">Email : <span style="font-weight : bold"><?php echo $this->infos['email']; ?></span></p>
<p style="margin-left : 30px">Adresse : 
	<span style="font-weight : bold"><?php echo $this->infos['adresse']; ?></span> - <span style="font-weight : bold"><?php echo $this->infos['codeP']; ?></span> <span style="font-weight : bold"><?php echo $this->infos['ville']; ?></span><br>
</p>
<br>
<p style="color:#F60; text-decoration : underline">Le Contrat</p>
<br>
<p style="margin-left : 30px">Le client a choisi un contrat <span style="font-weight : bold"><?php echo strtoupper($this->infos['contrat']); ?></span></p>
<?php if ($this->infos['hide'] == "carte") {?>
	<p style="margin-left : 30px">Le moyen de paiement choisi est <span style="font-weight : bold">le prélèvement banquaire automatique MENSUEL.</span></p>
	<p style="margin-left : 30px" style="color:green">Le contrat GAV prendra effet immédiatement dès réception de son RIB et de l'autorisation de prélèvement.<br>
	Ainsi, le client vous doit, chaque mois <span style="font-weight : bold"><?php echo ($this->infos['contrat'] == "Familial") ? 20 : 11 ?>€</span>.<br>
	Il faudra envoyer le contrat par voie postale à l'adresse ci-dessus.</p>
<?php } else { ?>
	<p style="margin-left : 30px">Le moyen de paiement choisi est <span style="font-weight : bold">le paiement par chèque ANNUEL.</span></p>
	<p style="margin-left : 30px" style="color:green">Le contrat GAV prendra effet immédiatement dès encaissement du chèque.<br>
	Ainsi, le client vous doit, pour cette année, un chèque de <span style="font-weight : bold"><?php echo ($this->infos['contrat'] == "Familial") ? 20*12 : 11*12 ?>€</span>.<br>
	Il faudra envoyer le contrat par voie postale à l'adresse ci-dessus.</p>
<?php } ?>
<?php if($this->infos['cg'] == 1) ?>
	<?php echo 'Enfin, le client à bien accepté les conditions générales de vente du contrat GAV.'; ?>

<br><br>Bonne journée</p>
<p style="margin:0 0 0 0; padding-bottom: 5px; font-size: 0.8em; border-bottom: 2px solid #e0e0e0;"><span style="margin-left:10px;">Ceci est un email automatique, merci de ne pas y répondre.</span></p>
<p style="margin: 5px 0 0 10px;"><a style="text-decoration:none;  font-weight:bold; " href="http://www.xylagroup.fr"><span style="color:#9ebad1;">www.</span><span style="color:#4c657d;">xylagroup</span><span style="color:#9ebad1;">.fr</span></a></p>
<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo $this->infos['controller']; ?> SARL au capital de 50 000 € / 492 320 320 Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07007951 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
</body>