<body>
<p>Bonjour, <br><br>En date du <?php echo $this->dateJour; ?>, la société <?php echo strtoupper($this->controller); ?> a reçu une demande de devis <strong>Dépendance</strong>.
<br>
<br>
Voici les informations relatives au demandeur <?php if($this->conjoint == "Oui") {echo 'ainsi que celles de '; echo ($this->civC == "Mme." || $this->civC == "Mlle.") ? "sa conjointe " : "son conjoint ";}?> :
<br>
<span style="font-weight:bold"><?php echo $this->civilite; ?> <?php echo $this->nom; ?> <?php echo $this->prenom; ?></span>, qui est le demandeur, est né<?php echo ($this->civilite == "Mme." || $this->civilite == "Mlle.") ? "e" : "";?> le <span style="font-weight:bold"><?php echo $this->date; ?></span><?php if($this->conjoint == "Oui") {echo ' et <span style="font-weight:bold">'.$this->civC.' '.$this->nomC.' '.$this->prenomC.'</span>, '; echo ($this->civC == "Mme." || $this->civC == "Mlle.") ? "sa conjointe, est née" : "son conjoint, est né"; echo ' le <span style="font-weight:bold">'.$this->dateC.'</span>';}?>.<br><br> L'adresse relative à la demande est : <br>
<span style="font-weight:bold"><?php echo $this->adresse; ?></span>
<br><br>
Son adresse e-mail est <?php echo $this->mail; ?> et son numéro de téléphone est le <span style="font-weight:bold"><?php echo $this->tel; ?></span>
<br>
Cette personne dispose d'une  <span style="font-weight:bold">rente de <?php echo $this->rente; ?></span>,  <span style="font-weight:bold"><?php echo ($this->depT == "Oui") ? "souhaite" : "ne souhaite pas";?></span> une dépendance totale, et  <span style="font-weight:bold"><?php echo ($this->depTP == "Oui") ? "souhaite" : "ne souhaite pas";?></span> une dépendance totale ou partielle.<br><br>Bonne journée</p>
<p style="margin:0 0 0 0; padding-bottom: 5px; font-size: 0.8em; border-bottom: 2px solid #e0e0e0;"><span style="margin-left:10px;">Ceci est un email automatique, merci de ne pas y répondre.</span></p>
<p style="margin: 5px 0 0 10px;"><a style="text-decoration:none;  font-weight:bold; " href=""><span style="color:#9ebad1;">www.</span><span style="color:#4c657d;">xylagroup</span><span style="color:#9ebad1;">.fr</span></a></p>
<p style="color:#435d74; margin-left : 13px; font-size: 0.7em"><?php echo $this->controller; ?> SARL au capital de 50 000 € / 492 320 320 Lyon / Société de Courtage en Assurances / NAF 6622Z / Siège Social : 3 Chemin de Parenty 69250 NEUVILLE SUR SAONE / 07007951 ORIAS / Inscriptions au registre des intermédiaires d’assurances vérifiables sur www.orias.fr</p>
</body>