## YAML Template
options:
 type: INNODB
 collate: utf8_general_ci
 charset: utf8

## News
News:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
   notnull: true
  titre: 
   type: string(100)
   notnull: true
  numero:
   type: integer
   notnull: true
  contenu: 
   type: string(10000)
   notnull: true
  auteur:
   type: string
   notnull: true
  lien:
   type: string
  photo:
   type: string
  image:
   type: string
   notnull: true
  date: 
   type: string
   notnull: true
  visible:
   type: string
   notnull: true

## Article page Erreur
Article:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
   notnull: true
  chapitre:
   type: string
   notnull: true
  numero:
   type: string
   notnull: true
  contenu:
   type: string
   notnull: true

## Users
Users:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
   notnull: true
  username:
   type: string()
   notnull: true
  password:
   type: string()
   notnull: true
  name:
   type: string()
   notnull: true
  droit:
   type: integer
   notnull: true


## Entite
Entite:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
   notnull: true
  nom: 
   type: string(20)
   notnull: true
  adresse: 
   type: string(200)
   notnull: true
 relations:
  Encadre:
   class: Encadre
   local: id
   foreign: entite_id
   foreignAlias: Entite
   foreignType: many
   type: many


## Encadre
Encadre:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
   notnull: true
  titre: 
   type: string(50)
   notnull: true
  contenu: 
   type: string(10000)
   notnull: true
  entite_id:
   type: integer
   notnull: true
  ordre :
   type: integer
   notnull: true
  ajout :
   type: string(1)
   notnull: true
  visible:
   type: string
   notnull: true
 relations:
  Entite:
   class: Entite
   local: entite_id
   foreign: id
   foreignAlias: Encadre
   foreignType: one
   type: one
  Sousencadre:
   class: Sousencadre
   local: id
   foreign: encadre_id
   foreignAlias: Encadre
   foreignType: many
   type: many


## SousEncadre
Sousencadre:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
   notnull: true
  titre: 
   type: string(50)
   notnull: true
  contenu: 
   type: string(10000)
   notnull: true
  encadre_id:
   type: integer
   notnull: true
  ordre :
   type: integer
   notnull: true
  visible:
   type: string
   notnull: true
 relations:
  Encadre:
   class: Encadre
   local: encadre_id
   foreign: id
   foreignAlias: Sousencadre
   foreignType: one
   type: one