<?php $this->headTitle()->append('Xylarisk'); ?>
<div class="logo">			
	<img src="<?php echo $this->baseUrl;?>/images/bandeaux/<?php echo $this->controller;?>.png" alt="<?php echo $this->controller;?>">
</div>
<br><br>
<h1>XYLARISK</h1>
<?php echo $this->partial('partials/affContenu.phtml', array(
							'controller' => $this->controller,
							'encadreEnti' => $this->encEnti)); ?>
	<!-- <div style="margin-left:17%" class="span9 columns">
	<br><br>
		<div id="myCarousel" class="carousel slide">
			<div class="carousel-inner">
				<div class="item active">
					<img src="<?php echo $this->baseUrl;?>/images/carousel/X_boot2.jpg" alt="Un X from the Bootstrap">
					<div class="carousel-caption">
						<h4>First X from the Bootstrap</h4>
						<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
					</div>
				</div>

				<div class="item">
					<img src="<?php echo $this->baseUrl;?>/images/carousel/city_1.jpg" alt="City">
					<div class="carousel-caption">
						<h4>Le sous titre sous la ville ??</h4>
						<p>Il faut tester sinon on ne saura jamais...ça serait dommage ;)</p>
					</div>
				</div>

				<div class="item">
					<img src="<?php echo $this->baseUrl;?>/images/carousel/X_boot.jpg" alt="Le X !!">
					<div class="carousel-caption">
						<h4>Le sous titre sous le Grand X ??</h4>
						<p>C'est Remy qui trouve qu'il fait bien ! C'est vrai que c'est cool comme image !</p>
					</div>
				</div>

			</div>
			<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>
	</div>
	<?php //$this->headScript()->captureStart() ?>
	<?php //$this->headScript()->captureEnd() ?>
	<!-- FIN CAROUSEL -->
